### ISSUE TITLE
Documentation unclear: Flux Kustomization patches do not apply over nested kustomizations

### ISSUE THREAD

**Issue by ondrejkolin** [fluxcd/kustomize-controller#1000]
We use following kustomizations structure in our projects:

`kustomize.config.k8s.io/v1beta1 -> kustomize.toolkit.fluxcd.io/v1 -> kustomize.toolkit.fluxcd.io/v1 -> helmrelease`

In my setup I have a patch on all top-level flux kustomizations with a patch for all helm releases - [full kustomization file](https://gitlab.com/ondrej.kolin/flux-helmrelease-patch-test/-/blob/3ad550972b108a10afac2d3d3913819a3ce952cb/cluster/flux-system/kustomization.yaml).

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- kustomization-in-the-middle.yaml
patches:
  - target: 
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      version: v1
    patch: |
      - op: add
        path: /spec/patches
        value:
          - target:
              kind: HelmRelease
            patch: |-
```

The patch is not delivered to the HR. This makes sense as when I do flux trace on that HR, it's only dependend on it's parent kustomization. 

Altough documentation mention writing patches at top-level Flux kustomization as a feature used in [bulk shard assignment](https://fluxcd.io/flux/installation/configuration/sharding/#bulk-assign-shards):

```
For example, assuming you want to assign a tenant to a particular shard, in the root Flux Kustomization that reconcile the tenant’s Flux sources, kustomizations and Helm releases label these resources as follows:
```
Image is a screenshot of the code from the documentation
![image](https://github.com/fluxcd/kustomize-controller/assets/2377891/0e92c4b3-f394-429f-8950-a8b46c8f3478)

I think that the documentation is wrong. I have a very minimal example where it's not working: https://gitlab.com/ondrej.kolin/flux-helmrelease-patch-test

**Comment by ondrejkolin** [comment]
IDEA: Recursive patches for `kustomize.toolkit.fluxcd.io`?

**Comment by Shane-UE** [comment]
I really like this idea, I am also trying to do nested patches, here is my example below:
`- patch: |
   - op: add path: /spec/patches
   - value: 
     - patch: |-
       - op: add path: /spec/chart/spec/sourceRef
       - value: 
         kind: GitRepository 
         name: zarf-charts 
    target:
      kind: HelmRelease
target: 
kind: Kustomization
namespace: flux-system`

DISCLAIMER, ignore indentation, our company doesn't allow pasting

**Comment by iAnomaly** [comment]
I would also really stand to benefit from a recursive patching feature.

We have a similar nested kustomization tree:
```
Kustomization/acme-system/acme-app
├── Namespace/acme-system
├── Kustomization/acme-system/api-controllers
│   ├── HelmRelease/acme-system/api
│   └── HelmChart/acme-system/api
├── Kustomization/acme-system/ui-controllers
│   ├── HelmRelease/acme-system/ui
│   └── HelmChart/acme-system/ui
└── GitRepository/acme-system/infrastructure
```

We're following the multi-tenancy model from https://github.com/fluxcd/flux2-multi-tenancy and https://github.com/controlplaneio-fluxcd/d1-fleet which requires patching `HelmRelease` and `Kustomization` resources:
1. `serviceAccountName`
2. `targetNamespace`

```
patches:
    - patch: |-
        kind: _
        metadata:
          name: _
        spec:
          serviceAccountName: flux
          targetNamespace: acme-system
      target:
        kind: (HelmRelease|Kustomization)
```

But...this only applies to the first layer/depth down. Any HelmRelease or Kustomization resources the next level down or deeper won't be patched. To get those we have to expand the patch as follows and would have to continue doing so for each layer of depth:

```
patches:
    - patch: |-
        kind: _
        metadata:
          name: _
        spec:
          serviceAccountName: flux
          patches:
            - patch: |-
                kind: _
                metadata:
                  name: _
                spec:
                  serviceAccountName: flux
              target:
                kind: (HelmRelease|Kustomization)
            - patch: |-
                kind: _
                metadata:
                  name: _
                spec:
                  serviceAccountName: flux-cluster
              target:
                kind: HelmRelease
                name: operator
      target:
        kind: (HelmRelease|Kustomization)
```

**Comment by memelet** [comment]
Yup, just spent a bit of time scratching my head on this. 
And since its typical for components to use patches, those are very limited as well.

Is this limitation documented?

**Comment by memelet** [comment]
Now I wonder if postBuild will recurse...

**Comment by rraodina** [comment]
Had success using [replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/). Easier to manage.
```
replacements:
  - source:
      kind: Kustomization
      name: one-of-them
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Kustomization
        fieldPaths:
          - spec.targetNamespace
        options:
          create: true
```
