### ISSUE TITLE
Postbuild substitution should substitute when kustomization have no substitution defined

### ISSUE THREAD

**Issue by NFRBEZ** [fluxcd/kustomize-controller#1011]
Postbuild substitution is not working when there is no substitution in kustomization : 

For example, the following kustomization 

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  path: ./apps/staging/my-app
  targetNamespace: my-app
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: my-app
      namespace: my-app
```

Generate me the following ressource

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: my-app
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: my-app
  namespace: my-app
spec:
  chart:
    ...
  values:
    metricsServer:
      dnsPolicy: ${dnsPolicy:=ClusterFirst}
      useHostNetwork: ${hostnetwork:="false"}
...
```

Which result on problem with my release installation
I need to add at least one postBuild argument to make the substitution occurs, even If it is not referred in my ressources
So doing like this :

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  path: ./apps/staging/my-app
  targetNamespace: my-app
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: my-app
      namespace: my-app
  postBuild:
    substitute:
      foo: bar
```

will work well :

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: my-app
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: my-app
  namespace: my-app
spec:
  chart:
    ...
  values:
    metricsServer:
      dnsPolicy: ClusterFirst
      useHostNetwork: "false"
...
```

**Comment by NFRBEZ** [comment]
Ok, got it
Wouldn't it be clearer to also add a postbuild.enabled field in the schema with a default to false, so we don't have to add a foo value on substitution array to enable substitution ?

This is a small change for a clearer view of it, as we wouldn't have to check on pointed folder if the variable is set somewhere. It would by default apply all default value

**Comment by stefanprodan** [comment]
If we add an enabled filed which defaults to false, then we'll break everyone's clusters, as this will skip the replacements even if there are in place, people will have to edit all their Flux Kustomizations to set enabled true. This type of change can't happen since the Kustomization API is v1 GA.

**Comment by NFRBEZ** [comment]
It depend of the implementation, postbuild would be implicit false without anything, enforced to true if enabled flag is set and defined to true if people defined any postbuild substitution in there kustomization. This way, people would not break theirs clusters.

Something there : https://github.com/fluxcd/kustomize-controller/blob/abdfab3dde0036f1712c3d1b6da90b276bace5a1/internal/controller/kustomization_controller.go#L621C33-L621C33

Which would change to something like the following :

```go
if obj.Spec.PostBuild != nil || obj.Spec.PostBuildEnforce {
```

**Comment by stefanprodan** [comment]
That will be very confusing, why would something still apply if it's set to `enabled: false`, none of Kubernetes API work like this. Just add a dummy substitution like this:

```yaml
  postBuild:
    substitute:
      enabled: "yes"
```

**Comment by ichekrygin** [comment]
(NOT A CONTRIBUTION), 
I'm surprised this is still an issue. Just hit this on:
```
flux: v2.8.3
distribution: flux-v2.8.5
helm-controller: v1.5.3
kustomize-controller: v1.8.3
notification-controller: v1.8.3
source-controller: v1.8.2
```

The gist: default-value substitution only works if at least one `substitute` variable is defined (even a dummy one).

I.e., with:
```yaml
foo: "${MYFOO:=bar}"
```

and:
```yaml
postBuild:
  substitute: {}
```

I get:
```yaml
foo: ${MYFOO:=bar}
```

but with:
```yaml
postBuild:
  substitute:
    buz: "by-design"
```

I get:
```yaml
foo: bar
```

Is this the correct understanding?
