### ISSUE TITLE
error decoding from JSON: illegal base64 data at input byte 3.

### ISSUE THREAD

**Issue by nilzen** [fluxcd/kustomize-controller#1020]
After commenting on the issue referenced at the bottom of this thread, I noticed that the issue had been closed, and my reply would probably never be picked up. Therefore, I'm creating a new issue here. I encountered the same problem while encrypting a secret with Age. The secret contained:

```yaml
data:
  token: YXN6ZTNxamh2azd2Yzh2OHAyMzZpcW96Nm9iOWJ0Cg==
```

In the cluster, I faced a decryption issue, receiving the error "error decoding from JSON: illegal base64 data at input byte 3." However, when I created the secret with `stringData` and encrypted it in the same way, the cluster decryption worked as expected:
 
 ```yaml
 stringData:
   token: asze3qjhvk7vc8v8p236iqoz6ob9bt
 ```

(Note: This is, of course, not a real token.)

flux version 2.1.2
age version 1.0.0
sops version 3.7.3

_Originally posted by @nilzen in https://github.com/fluxcd/kustomize-controller/issues/612#issuecomment-1839299908_

**Comment by mloskot** [comment]
@nilzen See my https://github.com/fluxcd/kustomize-controller/issues/612#issuecomment-1839369454

**Comment by stefanprodan** [comment]
We have a test for `data` here https://github.com/fluxcd/kustomize-controller/blob/main/internal/controller/testdata/sops/secret.day.yaml so I'm not sure how to replicate your issue.

**Comment by stefanprodan** [comment]
@somtochiama could you please look into this and see if the unit tests cover `data` with base64 in a Secret?

**Comment by nilzen** [comment]
Not sure I really follow what's missing @mloskot
I have a lab cluster created with `flux bootstrap` and I've appended the decryption part to the Kustomization in gotk-sync.yaml, probably not best practice but that's how I've done it now to test age/sops. So this is my full file that works with the value in plain text in `stringData` but not with a base64 encoded value in `data`:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/nilzen/nilzen-flux.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/nilzen-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
```
