### ISSUE TITLE
secretGenerator from file and postBuild substitution 

### ISSUE THREAD

**Issue by ndemeshchenko** [fluxcd/kustomize-controller#1089]
Hi,
Is there a way to achieve a `secretGenerator` to generate secret and substitute vars

```
...
secretGenerator:
  - name: additional-scrape-configs
    files:
      - prometheus-additional.yaml
```

when inside the prometheus-additional.yaml I want to use some vars of postBuild
