### ISSUE TITLE
Bug? Kustomization hangs when suspending a HelmRelease controlled by it

### ISSUE THREAD

**Issue by fllaca** [fluxcd/kustomize-controller#1100]
I have a kustomization that creates a Cilium HelmRelease. When I suspend the latter, either in the git config or by calling `flux suspend helmrelease cilium`, the Kustomization hangs and times out with this error:

```
pre-configuration        main@sha1:xxxxxx      False           False   Health check failed after 5m0.065267489s: timeout waiting for: [HelmRelease/kube-system/cilium status: 'InProgress']
```

This the  Kustomization spec:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: tenant-kustomizations
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: pre-configuration
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
  - name: previous-kustomization
  force: false
  interval: 10m0s
  path: ./somepath
  postBuild:
    substituteFrom:
     [ ... ] 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
```

And the HelmRelease spec:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: pre-configuration
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.14.6
  install:
    remediation:
      retries: 3
  interval: 15m
  releaseName: cilium
 values:
  [ ... ] 
```
