### ISSUE TITLE
Post build variable substitution not working after kustomize build

### ISSUE THREAD

**Issue by vijayansarathy** [fluxcd/kustomize-controller#1126]
I have been noticing a behavior with post build variable substitution which is causing health checks of Flux Kustomizations to fail. This used to work before but no longer does.

Flux CLI version: 2.1.2
Kustomize Controller: ghcr.io/fluxcd/kustomize-controller:v1.2.2
EKS: 1.29

The specific example use case is this:
I am using Crossplane AWS Provider in conjunction with Flux and creating certain AWS resources like IAM Roles and Policies. 
Here is the YAML manifest of one of my Kustomization resources.

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: awslbc-iam
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/infra/awslbc/iam/pia
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-source
  healthChecks:
  - kind: Role
    apiVersion: iam.aws.upbound.io/v1beta1
    name: eks-awslbc-serviceaccount-${cluster_name}-role
  - kind: Policy
    apiVersion: iam.aws.upbound.io/v1beta1
    name: eks-awslbc-serviceaccount-${cluster_name}-policy
  - kind: RolePolicyAttachment
    apiVersion: iam.aws.upbound.io/v1beta1
    name: eks-awslbc-serviceaccount-attachment
  - kind: PodIdentityAssociation
    apiVersion: eks.aws.upbound.io/v1beta1
    name: eks-awslbc-pia    
  timeout: 2m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
```

The ConfigMap used for variables substitution is as follows:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: flux-system
data:
  account_id: "0123456789012"
  aws_partition: aws
  aws_region: us-east-1
  cluster_arn: arn:aws:eks:us-east-1:0123456789012:cluster/sarathy-tf-129
  cluster_name: sarathy-tf-129
  cluster_security_group: sg-0ba495361f88a6078
  oidc_provider: oidc.eks.us-east-1.amazonaws.com/id/355DD0DA1A253048FDBA78CB9C819F2C
  vpc_id: vpc-47b16322
```

When the `awslbc-iam` Kustomization resource is synced to the cluster, it results in the creation of Crossplane custom resources that are defined by YAML manifests such as the one below:

```
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: eks-awslbc-serviceaccount-${cluster_name}-role
spec:
  providerConfigRef:
    name: default
  forProvider:
    assumeRolePolicy: |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "AllowEksAuthToAssumeRoleForPodIdentity",
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "pods.eks.amazonaws.com"
                    },
                    "Action": [
                        "sts:AssumeRole",
                        "sts:TagSession"
                    ]
                }
            ]
        }   
```
The variable substitution works fine when the custom resources are created. So, a `Role` with the name `eks-awslbc-serviceaccount-sarathy-tf-129-role` gets created. However, the substitution does not take place for the variables that are used in the `healthChecks` section of the Kustomization.

When I run the command `kubectl -n flux-system get kustomization awslbc-iam -o yaml`, the following is what I see in the spec.healthChecks section. 

```
spec:
  force: false
  healthChecks:
  - apiVersion: iam.aws.upbound.io/v1beta1
    kind: Role
    name: eks-awslbc-serviceaccount-${cluster_name}-role
  - apiVersion: iam.aws.upbound.io/v1beta1
    kind: Policy
    name: eks-awslbc-serviceaccount-${cluster_name}-policy
  - apiVersion: iam.aws.upbound.io/v1beta1
    kind: RolePolicyAttachment
    name: eks-awslbc-serviceaccount-attachment
  - apiVersion: eks.aws.upbound.io/v1beta1
    kind: PodIdentityAssociation
    name: eks-awslbc-pia
```

I expected the `${cluster_name}` variable to be replaced by the value `sarathy-tf-129`. I clearly recall seeing this behavior earlier (unfortunately I don't have the versions of Flux that I used at that time) and the health checks used to pass. But now, the heath checks fail with the following error from the Kustomize controller logs.

`{"level":"error","ts":"2024-04-04T23:03:25.692Z","msg":"Reconciliation failed after 2m0.253643781s, next try in 1m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"awslbc-iam","namespace":"flux-system"},"namespace":"flux-system","name":"awslbc-iam","reconcileID":"616775f8-59fc-481c-87de-3ceadac778c2","revision":"main@sha1:dca09e71556f278b5fa0d57b89448e3fd275a286","error":"health check failed after 2m0.019874979s: timeout waiting for: [Role/eks-awslbc-serviceaccount-${cluster_name}-role status: 'NotFound', Policy/eks-awslbc-serviceaccount-${cluster_name}-policy status: 'NotFound']"}`
