### ISSUE TITLE
SOPS: Decryption does not work for envs in secretGenerator

### ISSUE THREAD

**Issue by Do-min-ik** [fluxcd/kustomize-controller#1271]
## Description
I'm trying to use SOPS to replace plaintext secrets in my .env files with encrypted ones. However, I can't get fluxcd to actually decrypt `Secret`s generated by  `secretGenerator` and `envs`.

## Example
I'm using the example from #463:

Create an env file:
```
ROUTER_PASSWORD=admin
DB_PASSWORD=admin
``` 

Encrypt it with SOPS:
```
sops --encrypt --in-place podinfo.env
```
Create a kustomization.yaml that generates an env secret:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
secretGenerator:
  - name: env-secret
    envs:
      - podinfo.env
```

Configure Flux to decrypt the secret before apply:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1m0s
  path: ./secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

**Expected behavior:**  `secrets` contains the unencrypted values of ROUTER_PASSWORD and DB_PASSWORD
**Actual behavior:**  `secrets` is actually still encrypted and contains SOPS info

## Version
I first encountered this behavior in version 2.3.0 but have since upgraded to version 2.4.0.

**Comment by vlasov-y** [comment]
Do you have .sops.yaml in the root of the repo?

```yaml
creation_rules:
  - path_regex: podinfo.env
    key_groups:
      - age:
          - age1qwer1234 # Your key goes here
```
