### ISSUE TITLE
Nested Kustomizations and prune

### ISSUE THREAD

**Issue by bozho** [fluxcd/kustomize-controller#1279]
Hi all,

I'm trying to understand `prune` behaviour when using nested kustomizations. I hit this problem when trying to create a test repository with composable components, following [this](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md).

I created a minimal sample trying to figure it out. My directories look like this:
```
├── clusters
|   └── k8s-small
|       ├── flux-system
|       ├── kustomization.yaml
|       └── podinfo.yaml
|
└── platform
    └── podinfo
        └── _base
            ├── kustomization.yaml
            └── podinfo.yaml
```

```yaml
# clusters/k8s-small/kustomization.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo.yaml
```

```yaml
# clusters/k8s-small/podinfo.yaml

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./platform/podinfo/_base
  prune: false
  wait: true
  timeout: 5m
```

```yaml
# platform/podinfo/_base/kustomization.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo.yaml
```

```yaml
# platform/podinfo/_base/podinfo.yaml

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
  timeout: 3m0s
  wait: true
```

When `prune` is `false` in both Kustomizations, `podinfo` resources get created as expected.

When I set `prune` to `true` only in the "parent" Kustomization (`clusters/k8s-small/podinfo.yaml`), any running `podinfo` pods get deleted and then redeployed.

`flux logs` shows these lines:
```
2024-11-04T15:30:27.688Z info Kustomization/podinfo.flux-system - server-side apply completed
2024-11-04T15:30:27.825Z info Kustomization/podinfo.flux-system - garbage collection completed: HorizontalPodAutoscaler/default/podinfo deleted
Deployment/default/podinfo deleted
Service/default/podinfo deleted
2024-11-04T15:30:28.029Z info Kustomization/podinfo.flux-system - Reconciliation finished in 604.521568ms, next run in 15m0s
2024-11-04T15:30:28.327Z info Kustomization/podinfo.flux-system - server-side apply completed
2024-11-04T15:30:58.499Z info Kustomization/podinfo.flux-system - Reconciliation finished in 30.468408748s, next run in 30m0s
```

When I set `prune` to `true` only in the "child" Kustomization (`platform/podinfo/_base/podinfo.yaml`), any running `podinfo` pods get deleted.

When I use the simple `podinfo` Kustomization structure from `flux` tutorial, everything works as expected, with `prune` set to `true`.
