### ISSUE TITLE
karpenter NodePool dry-run failed

### ISSUE THREAD

**Issue by EigoOda** [fluxcd/kustomize-controller#1296]
I enabled conversion webhook when I upgraded Karpener to v1.
However, the Karpenter Pod was giving frequent TLS handshake errors and was noisy, so I disabled the Karpenter webhook.
The noisy logs disappeared, but the kustomization resource failed to dry-run the webhook and was no longer READY, so I re-enabled the webhook.
I re-enabled webhook, but now it continues to not READY with the following message.

```text
NodePool/nodepool dry-run failed (Invalid): NodePool.karpenter.sh "nodepool" is invalid: [spec.disruption.consolidateAfter: Required value, <nil>: Invalid value: "null": some validation rules were no
t checked because the object was invalid; correct the existing errors to complete validation]
```

I had no problems until I upgraded to v1 and disabled webhooks.
And nodepool schema is correct and I can apply with kubectl apply without above error.
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["m6i"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["16", "32", "48"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: nodeclass
      expireAfter: 720h # 30days
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    budgets:
      - nodes: 25
```

I tried to re-create the kustomization resource doesn't work.

Do you have any ideas?
Thanks.
