### ISSUE TITLE
kustomization skips part of the CRD manifest

### ISSUE THREAD

**Issue by andrii-roche** [fluxcd/kustomize-controller#1327]
I'm trying to deploy karpenter's `ec2nodeclass.karpenter.k8s.aws` which recently got a new field `spec.kubelet` (moved from other crd)

Here is the file in my Git:
```
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-arm
spec:
  amiFamily: AL2
  amiSelectorTerms:
    - id: ami-1234
  kubelet:
    # set same reservations as in base node group
    evictionHard:
      memory.available: 0.5Gi
      nodefs.available: 10%
      nodefs.inodesFree: 10%
    evictionMaxPodGracePeriod: 60
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
...
```

When I apply it manually with kubectl, it works well:
```
$ kubectl get ec2nodeclass.karpenter.k8s.aws/default-arm -o yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: karpenter-configuration
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: default-arm
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - id: ami-1234
  kubelet:
    evictionHard:
      memory.available: 0.5Gi
      nodefs.available: 10%
      nodefs.inodesFree: 10%
    evictionMaxPodGracePeriod: 60
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
...
```

but when I apply it with flux, e.g. `flux reconcile kustomization --with-source -n flux-system   karpenter-configuration`, I get the manifest without the `kubelet` part:
```
$ kubectl get ec2nodeclass.karpenter.k8s.aws/default-arm -o yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: karpenter-configuration
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: default-arm
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - id: ami-1234
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
```

I'm using the latest component versions, e.g. kustomize-controller `v1.4.0`
