### ISSUE TITLE
PostBuild substitution not working for secretGenerator with literals

### ISSUE THREAD

**Issue by crazyelectron-io** [fluxcd/kustomize-controller#1336]
I have a Git repo with two Kustomizations: for a CloudnativePG database and for a workload using that DB. It needs a secret to specify the username/password for DB connection. Somehow the variables are not substituted in the CloudnativePG Kustomization, but they are in the workload Kustomization.

The 'root' Kustomization:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./namespace.yaml
  - ./cnpg/kustomization-flux.yaml
  - ./app/kustomization-flux.yaml
```
The 'cnpg' Flux Kustomization:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-app-cnpg
spec:
  path: ./app/cnpg/base
  sourceRef:
    kind: GitRepository
    name: app
    namespace: flux-system
```
The 'cnpg/base' Kustomization using the `secretGenerator`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./cluster.yaml
secretGenerator:
  - name: app-cnpg-user-secret
    literals:
      - username=${SECERT_APP_PG_USERNAME}
      - password=${SECRET_APP_PG_PASSWORD}
    type: 'kubernetes.io/basic-auth'
generatorOptions:
  disableNameSuffixHash: true
```

The two variables are specified in `cluster-secret-vars` and patched in the `postBuild` of the Kustomization referencing the app/database Git Source repo:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  path: ./app
  sourceRef:
    kind: GitRepository
    name: app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - kind: Secret
                name: cluster-secret-vars
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
```
Note: I left out a few details like referencing the SOPS key, to keep it simple.

When running the Kustomizations, those two variables are not replaced  with their value. However, in the other Kustomization in the same Git Source repo, for the application, the patching works fine.

The 'app' Flux Kustomization:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automation-app
spec:
  path: ./app/app/base
  sourceRef:
    kind: GitRepository
    name: app
    namespace: flux-system
```
The 'app/base' Kustomization, using `configMapGenerator`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./app-deployment.yaml
configMapGenerator:
  - name: app-config
    files:
      - configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
```
The parameters in `configuration.yaml` get replaced with the value from the secret `cluster-secret-vars`.  The file looks like:
```yaml
  ...
database:
  db_url: postgresql://${SECRET_APP_PG_USERNAME}:${SECRET_APP_PG_PASSWORD}@...
  ...
```
The difference being that this works with a file with the variables and the non-working scenario works with literals for generating the output. Also, the generated result is a ConfigMap in the working scenario and a Secret in the non-working scenario.

Could this be Flux related? Is the `postBuild` patching done after the secretGenerator literals are generated? Or could this be a Kubernetes Customise issue (or a user error...)?
