### ISSUE TITLE
Default value ignore in substitute

### ISSUE THREAD

**Issue by yodamad** [fluxcd/kustomize-controller#1350]
Hi,

I'm trying to use `substitute` mechanism with a default value.

Current version of flux : `ghcr.io/fluxcd/kustomize-controller:v1.4.0`

So I defined a `Namespace`object : 
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${frontend_ns_name:=dev}
```

And define my `GitRepository` and `Kustomization` but without overriding the default value for my default env.

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: commons-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: feat/fluxcd
  timeout: 60s
  url: https://gitlab.com/xxx/demo/manifests.git
```

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-demo-frontend
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./frontend
  prune: true
  sourceRef:
    kind: GitRepository
    name: commons-gitops
```

When Flux try to reconcile the information, it fails explaining that the value is not valid : 

```sh
Reconciliation failed after 150.548712ms, next try in 1m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"flux-demo-frontend","namespace":"flux-system"},"namespace":"flux-system","name":"flux-demo-frontend","reconcileID":"5ed498e8-b838-42e1-8d82-dc6671ae7f3a","revision":"feat/fluxcd@sha1:4aa0ecf8882974ab1c8670e457f6ff6cb26544a9
[...]
"Namespace/${frontend_ns_name:=dev} dry-run failed (Invalid): Namespace \"${frontend_ns_name:=dev}\" is invalid: [metadata.name: Invalid value: \"${frontend_ns_name:=dev}\": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-' ...
```

Don't know what I'm doing wrong here as I think that I follow correctly the doc [sample](https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution)

**Comment by yodamad** [comment]
If I add the configuration : 
```yaml
  postBuild:
    substitute:
      frontend_ns_name: "dev"
```

It works, but I suppose that default value should work without this

**Comment by wombat** [comment]
@yodamad I experienced the same in the beginning. The docs say:
`Substitution of variables only happens if at least a single variable or resource to substitute from is defined. This may cause issues if you rely on expressions which should evaluate to a default value, even if no other variables are configured. To work around this, one can set an arbitrary key/value pair to enable the substitution of variables`.

So having variables implies that you need to do any substitution in order to activate it (even for defaults).

The docs also recommends this as an example:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
spec:
  # ...omitted for brevity
  postBuild:
    substitute:
      var_substitution_enabled: "true"
```

Hope this helps :)
