### ISSUE TITLE
Support SOPS Decryption with key in different namespace

### ISSUE THREAD

**Issue by jdorel** [fluxcd/kustomize-controller#1363]
# Current Situation

When using SOPS Decryption in a Kustomization, the secret containing the decryption key has to be in the same namespace as the Kustomization.
This seems to be coded there : https://github.com/fluxcd/kustomize-controller/blob/281d998261adc58531bf1093c2bc220b736daf6e/internal/decryptor/decryptor.go#L207

# Desired Situation

I would like to be able to use a key from a different namespace, using the following key : `kustomization.Spec.Decryption.SecretRef.namespace`.
Should this field be empty, the key should be searched in the kustomization namespace as currently.

# My use case

I'm have the following files :
```
app-alpha.flux-kustomization.yaml
app-beta.flux-kustomization.yaml
kustomization.yaml
```

In kustomization.yaml, I have the following :
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-alpha.flux-kustomization.yaml
  - app-beta.flux-kustomization.yaml
patches:
  - target:
      kind: Kustomization
    patch: |
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: ignored-but-required
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
```

The decryption secret is in the `flux-system` namespace. While app-alpha and app-bravo kustomization are in there dedicated app namespaces.
