### ISSUE TITLE
Unable to decrypt a secret via SOPS

### ISSUE THREAD

**Issue by kamialie** [fluxcd/kustomize-controller#1371]
With the recent upgrade to kustomize controller to v1.5.0 I'm facing the following issue during reconciliation:
```
Warning  BuildFailed              2m40s              kustomize-controller  decryption failed for 'foo-token': failed to decrypt and format 'default/foo-token' Secret data: error decrypting sops tree: Error walking tree: Could not decrypt value: Input string glagent-xxx does not match sops' data format
```

I have a secret resource which is set to empty string in the base layer, and there is a patch that contains actual secret data. Both of them are encrypted using SOPS (and AWS KMS key, but I think that's irrelevant here). To my surprise kustomize controller shows the secret value itself (in the logs!), and that's probably the hint as well why it fails. I suspect kustomize is trying to decrypt the secret twice, so on the second attempt SOPS obviously complains that the passed in [value doesn't match the regex it expects](https://github.com/getsops/sops/blob/063e054abd666719568894f2cdaf97fddccc447c/aes/cipher.go#L60).

I confirmed that my GitOps repo sucessfully reconciles with kustomize controller v1.4.0, and does not with v1.5.0.  I believe the cullprit is [here](https://github.com/fluxcd/kustomize-controller/pull/1286), but I'm lacking background knowledge and local setup to confirm though.

**Comment by kamialie** [comment]
Going through code I guess the assumption at the moment is that base layer is not encrypted, while the patch is. The latest version of the controller would basically simply decrypt _earlier_. The reason I encounter the error is probably due to base layer containing SOPS metadata, so controller thinks it needs to decrypt that source file, where patch (with already decrypted data) has been applied to. If my assumptions are correct, I can see how I can immediately fix the issue by just removing SOPS metadata from base layer, since encrypting empty string barely serves any purpose, but I can see how this can still not work for everyone. For instance, what if I simply won't to rotate a shared secret across environments: my current value would be in the base layer (to avoid duplication), and I'm introducing new value in dev environment.

**Comment by matheuscscp** [comment]
Hi @kamialie I'm investigating this bug right now, can you please share more details of how your config is structured? Possibly the exact thing except for the actual secret values of course. Much appreciated! 🙏 

Also pinging @vlasov-y, your two PRs #1283 and #1286 seem to be the only ones touching decryption in the [change log for kustomize-controller v1.5.0](https://github.com/fluxcd/kustomize-controller/blob/main/CHANGELOG.md#150), if you could please shed some light here 🙏

**Comment by kamialie** [comment]
Hi @matheuscscp, yes of course! Please, let me know, if the structure/file contents below make sense:
```yaml
# ./infra/base/agent/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
```

```yaml
# ./infra/base/agent/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: token
type: Opaque
stringData:
    token: ""
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:1234567890:key/...
          <...>
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
```

```yaml
# ./infra/base/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: addons
resources:
  - agent
```

```yaml
# ./infra/dev/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: agent.secret.patch.yaml
```

```yaml
# ./infra/dev/agent.secret.patch.yaml
apiVersion: v1
kind: Secret
metadata:
    name: token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:foobar,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:1234567890:key/...
          <...>
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
```

Also, I just noticed, if I set value to empty string, SOPS doesn't even bother to encrypt it (rightfully), but I sort of doubt that changes much in our context.
