### ISSUE TITLE
Unable to patch encrypted secret

### ISSUE THREAD

**Issue by jkotiuk** [fluxcd/kustomize-controller#1382]
I'd like to follow up on #1371 

I've upgrade kustomize controller from v1.4.0 to v1.5.1 and I'm getting errors on `Secrets` that are patched in overlays:

```
decryption failed for 'acp-tests': failed to decrypt and format 'acp-tests-sa/acp-tests' Secret data: error decrypting sops tree: Error walking tree: Could not decrypt value: Input string <redacted> does not match sops' data format
```

My base secret:
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: acp-tests
  namespace: acp-tests
stringData:
  acpSecret: ENC[AES256_GCM,data:ewYNYGH+X+bSpWAWM6AK3g6F26Bhw8EdK5LIXK0Bet0=,iv:bpF3p3P3xUjKHwFg3IcD7KZLYyumfERjED+lv62Bfh0=,tag:m4iMG1/Tn9LAVnhBpzjPmA==,type:str]
  identitySecret: ENC[AES256_GCM,data:iAzMABifmexcDZaxVjvMzXDeSNHKhf3j++2YifQhrgs=,iv:EVK5GQE8vYVBDyvSKpJuYfim4RhM3q0SY5tOTrzL0Sw=,tag:9yolgauhvBXfv9kjQT0ZaA==,type:str]
  mailosaurApiKey: ENC[AES256_GCM,data:FkHlbYZIF2etSFXYIrqFjA==,iv:8DOy/grkHNXlg4dv/kOkxqNG1vw/mNpir7J8ZVweJYU=,tag:imU+3r+jTd+5VvaM8y62Rg==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:645335760782:key/5dcc199b-4fb9-4ab5-b85d-7cf9ee1e26dd
      created_at: "2021-08-26T08:02:51Z"
      enc: AQICAHjUgu09am4Qfql3fQJmM9AgNvGS14AFJjAVnNvUKxCzfQH6WbBn4yUSR/LfM9xipIo2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1uKURLJyz1UBWUw4AgEQgDtftgNzIMhIz5mHg2XxG9nU4Hoi/Znm45asvhKQ8jdcYT/tXgB1NH3vFq/nPQXYrPoO3rsVRQsl328a+A==
      aws_profile: ""
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-07-02T10:55:59Z"
  mac: ENC[AES256_GCM,data:1q4UB80Vf9oNu+rARMkJM7gFJmJ9umxexdxlxF08ATbtWpiQC+uEuG8ZGRuX6GCTQuSG8r/VSd3PeNDJDz80RKHpoWmAKbjgwn93gBnfLRWdz6dtWPotzznBKKycidNbStznzlIpgUU355Mv2GzPHxspzBbq/PbkWIBvk3aDKGk=,iv:fXoGa48soBQyUCHg8xv6FpqCe5fnGmSvAGly5d54EJM=,tag:/HBj7Hg266lGDPOIX/QsCQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
```

My patch:
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: acp-tests
    namespace: acp-tests
stringData:
    acpSecret: ENC[AES256_GCM,data:ewYNYGH+X+bSpWAWM6AK3g6F26Bhw8EdK5LIXK0Bet0=,iv:bpF3p3P3xUjKHwFg3IcD7KZLYyumfERjED+lv62Bfh0=,tag:m4iMG1/Tn9LAVnhBpzjPmA==,type:str]
    identitySecret: ENC[AES256_GCM,data:iAzMABifmexcDZaxVjvMzXDeSNHKhf3j++2YifQhrgs=,iv:EVK5GQE8vYVBDyvSKpJuYfim4RhM3q0SY5tOTrzL0Sw=,tag:9yolgauhvBXfv9kjQT0ZaA==,type:str]
    mailosaurApiKey: ENC[AES256_GCM,data:qIZS3NMobmSi3hJ2aqqiaqAxnCH1wAbu6Uc/5ka9aJs=,iv:VTDqHrYhlDZykj9JTfFOf/v30IcQh4fJ6xZ5vjlNfDc=,tag:nswzPQScwCp+MRjlmPuaaw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:645335760782:key/5dcc199b-4fb9-4ab5-b85d-7cf9ee1e26dd
          created_at: "2021-08-26T08:02:51Z"
          enc: AQICAHjUgu09am4Qfql3fQJmM9AgNvGS14AFJjAVnNvUKxCzfQH6WbBn4yUSR/LfM9xipIo2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1uKURLJyz1UBWUw4AgEQgDtftgNzIMhIz5mHg2XxG9nU4Hoi/Znm45asvhKQ8jdcYT/tXgB1NH3vFq/nPQXYrPoO3rsVRQsl328a+A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-04T11:25:50Z"
    mac: ENC[AES256_GCM,data:8MXFJLHK4f5pCJRRj0ZobIHFVhRz5SIqBecxWWWK5o+/+zBgbZfOypswOwnG9MW/e7pNpH/Eut5Tk7JHS/2309j7JsNGUFeZT4sL/+XDc+K+CgUHcaSK8MCqx+IVkzFdW5Ifr2/2zdKg808UcgKj4Olr/HGsM+Y7h8DZyBhVND0=,iv:x4GXDS49e6k0Xr6H263LjY9EnR1LqjsMK7eIXKQi8L8=,tag:xonprfILxRqNkgXfyigZDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
```

Overlays kustomization:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp-tests-sa
resources:
- ../base
patches:
  - path: secret.yaml
```

I'm not sure what changed, but above setup was working on 1.4.0

I've tried to include secret as a new file and remove previous one by changing kustomization, but that gives me other error that secret already exists

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp-tests-sa
resources:
- ../base
- secret.yaml
patches:
  - target:
      kind: Secret
      name: acp-tests
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: acp-tests
```

The above kustomization results in

```
Error: accumulating resources: accumulation err='merging resources from 'secret.yaml': may not add resource with an already registered id: Secret.v1.[noGrp]/acp-tests.acp-tests'
```

Is it not possible to patch secrets since 1.5.0 of the kustomization controller? Is there any workaround for this?

**Comment by matheuscscp** [comment]
https://github.com/fluxcd/kustomize-controller/issues/1371

cc @vlasov-y

**Comment by jkotiuk** [comment]
> See this: [#1371](https://github.com/fluxcd/kustomize-controller/issues/1371)
> 
> cc [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/vlasov-y?size=32">@vlasov-y](https://github.com/vlasov-y)

Look at the first line of my post :)

So you are saying that the only way to patch secrets is to use `secretGenerator` ?

**Comment by vlasov-y** [comment]
> > See this: [#1371](https://github.com/fluxcd/kustomize-controller/issues/1371)
> > cc [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/vlasov-y?size=32">@vlasov-y](https://github.com/vlasov-y)
> 
> Look at the first line of my post :)
> 
> So you are saying that the only way to patch secrets is to use `secretGenerator` ? I'd rather avoid refactoring all my existing secrets. If this is true, it should be pointed in the release notes.

TL;DR - move all your secrets from resources files to patches files or files/envs generator files.

**Comment by jkotiuk** [comment]
> > > See this: [#1371](https://github.com/fluxcd/kustomize-controller/issues/1371)
> > > cc [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/vlasov-y?size=32">@vlasov-y](https://github.com/vlasov-y)
> > 
> > 
> > Look at the first line of my post :)
> > So you are saying that the only way to patch secrets is to use `secretGenerator` ? I'd rather avoid refactoring all my existing secrets. If this is true, it should be pointed in the release notes.
> 
> TL;DR - move all your secrets from resources files to patches files or files/envs generator files.

I don't get it, my secret is in the patch file as included in kusomization. Could you elaborate more on patches file approach?

```
patches:
  - path: secret.yaml
```

secret.yaml
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: acp-tests
    namespace: acp-tests
stringData:
    acpSecret: ENC[AES256_GCM,data:ewYNYGH+X+bSpWAWM6AK3g6F26Bhw8EdK5LIXK0Bet0=,iv:bpF3p3P3xUjKHwFg3IcD7KZLYyumfERjED+lv62Bfh0=,tag:m4iMG1/Tn9LAVnhBpzjPmA==,type:str]
    identitySecret: ENC[AES256_GCM,data:iAzMABifmexcDZaxVjvMzXDeSNHKhf3j++2YifQhrgs=,iv:EVK5GQE8vYVBDyvSKpJuYfim4RhM3q0SY5tOTrzL0Sw=,tag:9yolgauhvBXfv9kjQT0ZaA==,type:str]
    mailosaurApiKey: ENC[AES256_GCM,data:qIZS3NMobmSi3hJ2aqqiaqAxnCH1wAbu6Uc/5ka9aJs=,iv:VTDqHrYhlDZykj9JTfFOf/v30IcQh4fJ6xZ5vjlNfDc=,tag:nswzPQScwCp+MRjlmPuaaw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:645335760782:key/5dcc199b-4fb9-4ab5-b85d-7cf9ee1e26dd
          created_at: "2021-08-26T08:02:51Z"
          enc: AQICAHjUgu09am4Qfql3fQJmM9AgNvGS14AFJjAVnNvUKxCzfQH6WbBn4yUSR/LfM9xipIo2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1uKURLJyz1UBWUw4AgEQgDtftgNzIMhIz5mHg2XxG9nU4Hoi/Znm45asvhKQ8jdcYT/tXgB1NH3vFq/nPQXYrPoO3rsVRQsl328a+A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-04T11:25:50Z"
    mac: ENC[AES256_GCM,data:8MXFJLHK4f5pCJRRj0ZobIHFVhRz5SIqBecxWWWK5o+/+zBgbZfOypswOwnG9MW/e7pNpH/Eut5Tk7JHS/2309j7JsNGUFeZT4sL/+XDc+K+CgUHcaSK8MCqx+IVkzFdW5Ifr2/2zdKg808UcgKj4Olr/HGsM+Y7h8DZyBhVND0=,iv:x4GXDS49e6k0Xr6H263LjY9EnR1LqjsMK7eIXKQi8L8=,tag:xonprfILxRqNkgXfyigZDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
```

**Comment by vlasov-y** [comment]
If you have some common secrets for both overlays, you may do.

```shell
#!/usr/bin/env bash

mkdir -p ./base
cat >./base/kustomization.yaml <<EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: acp-tests
    namespace: acp-tests
    envs:
      - secret.sops.env
    options:
      disableNameSuffixHash: true
EOF

mkdir -p ./base
cat >./base/secret.sops.env <<EOF
some=commons
secret=values
EOF

... Rest is the same
```

**Comment by stefanprodan** [comment]
@jkotiuk you need to change the base secret to:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: acp-tests
  namespace: acp-tests
```

Starting with Flux 2.5 we no longer accept both base and patch encrypted files, you can only encrypt the patches while the base should contain a blank Secret.

**Comment by vlasov-y** [comment]
@stefanprodan I feel a bit guilty for the PR with SOPS changes. Should we update the documentation to include such cases description?

**Comment by jkotiuk** [comment]
Thank you for your explanation, I'll make the required changes to my code.

**Comment by stefanprodan** [comment]
I'm really surprised people use patches for Secrets. Like in the example above, there shouldn't be a patch, the whole secret is replaces which means a patch is useless. Instead of having the Secret in base, they overlay could just have the secret in `resources`.

**Comment by jkotiuk** [comment]
@stefanprodan My use case is that kustomization doesn't allow you to add `resources` if it already exists in base layer.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp-tests-sa
resources:
- ../base
- secret.yaml
```

This gives below error as secret already exists in base layer, so easiest way to update it was to patch as a whole.
```
Error: accumulating resources: accumulation err='merging resources from 'secret.yaml': may not add resource with an already registered id: Secret.v1.[noGrp]/acp-tests.acp-tests'
```

My sample directory structure.
```
overlays/
└── preprod/
    └── base/  # Secret definitions encrypted with preprod KMS
        ├── namespace_x/  # Uses base secret
        ├── namespace_y/  # Uses base secret
        ├── namespace_z/  # Uses base secret
        ├── namespace_custom/  # Uses unique secret values
```
It would require me to add an additional layer that will remove secret for namespace_custom.

I've tried kustomization like below but it didn't work. Maybe there is some other solution to include it as a `resource` and not getting duplicate error.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp-tests-sa
resources:
- ../base
- secret.yaml
patches:
  - target:
      kind: Secret
      name: acp-tests
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: acp-tests
```
