### ISSUE TITLE
Constant resources recreation

### ISSUE THREAD

**Issue by aprohorov-callsign** [fluxcd/kustomize-controller#1419]
Hey team!

Faced with interesting issue. Have a service with CRD where I need to change the Image, but for some reason the controller every refresh interval (1 minute in my case) apply original manifest, and then modified. As the result pods terminating and creating every minute.

My config:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-infra-services-crowdstrike-falcon-sensor
spec:
  force: false
  interval: 1m
  path: ./sandbox/my-service
  prune: true
  images:
    - name: original-image-name
      newName: my-custom-name
      newTag: my-tag
  sourceRef:
    kind: GitRepository
    name: my-git-repo
```
my-service configuration:
```
# kustomization.yaml
resources:
  - https://github.com/my-service/original-manifest.yaml

configurations:
  - image-transform.yaml

patches:
  - patch: |
      - op: replace
        path: /spec
        value:
          node:
            image: original-image-name:latest
    target:
      kind: MyCRD
      name: my-service

#  image-transform.yaml
images:
  - path: spec/node/image
    kind: MyCRD
```

as the result, my CRD resource spec changed every minute:
```
spec:
  node:
    image: original-image-name:latest
```
then instantly to
```
spec:
  node:
    image: my-custom-name:my-tag
```

As for now I've fixed it by moving `image` section to `kustomization.yaml`. So in the next configuration it works
```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-infra-services-crowdstrike-falcon-sensor
spec:
  force: false
  interval: 1m
  path: ./sandbox/my-service
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-git-repo
```
my-service configuration:
```
# kustomization.yaml
resources:
  - https://github.com/my-service/original-manifest.yaml

configurations:
  - image-transform.yaml

images:
  - name: original-image-name
    newName: my-custom-name
    newTag: my-tag

patches:
  - patch: |
      - op: replace
        path: /spec
        value:
          node:
            image: original-image-name:latest
    target:
      kind: MyCRD
      name: my-service

#  image-transform.yaml
images:
  - path: spec/node/image
    kind: MyCRD
```
