### ISSUE TITLE
What is the meaning of `sourceRef`?

### ISSUE THREAD

**Issue by Sleepful** [fluxcd/kustomize-controller#1420]
AFAIK it is meant to reference a `GitRepository` kind, one such example is in the [docs](https://fluxcd.io/flux/components/kustomize/kustomizations/#example):
```yml
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
```
...
```yml
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  sourceRef:
    kind: GitRepository
    name: podinfo
```
so here the `sourceRef.name` is pointing to the `GitRepository` from above.

But I am confused by examples using `sourceRef.name: flux-system`:

```yml
  sourceRef:
    kind: GitRepository
    name: flux-system
```

Which `GitRepository` resource would this be pointing at?

I would expect it to point to a resource like the following, but it is not present in the examples:

```yml
kind: GitRepository
metadata:
  name: flux-system
  namespace: default
```

**Edit**: it seems that the `flux-system` repo is generated by `bootstrap`, and this is why it is not shown in the examples. Do you think I could add this to the docs?
