### ISSUE TITLE
Slower Reconciles with v1.5.1

### ISSUE THREAD

**Issue by ChuckQuinnIV** [fluxcd/kustomize-controller#1428]
When upgrading from kustomize-controller `1.5.0` to `1.5.1`, we're seeing a significant slowdown in reconcile times.

Using one Kustomization as an example, which manages ~1500 NetworkPolicies:

Average reconcile time on `1.5.0`: 25s
Average reconcile time on `1.5.1`: 2m30s

Example Kustomization setup:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-kustomize
spec:
  force: false
  interval: 60m
  path: ./path/to/netpols
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-repo
```
