### ISSUE TITLE
Feature Request: Optional Components (ignoreMissingComponents)

### ISSUE THREAD

**Issue by Preisschild** [fluxcd/kustomize-controller#1440]
## Summary

Add the possibility of specifying `.spec.components` that just won't be included when they are not there via another field (possibly `.spec.ignoreMissingComponents`, similar to ArgoCD)

This would allow users to use a repository structure where, for example in a multicluster repo, you could define cluster specific overrides to an application just by creating a 
directory

Example:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  # ...omitted for brevity
  ignoreMissingComponents: true
  components:
  - ./clusters/${cluster}
```

There is already a precedent for this sort of stuff in the flux helm-controller. It also implements `ignoreMissingValuesFiles` similar to ArgoCD: https://github.com/fluxcd/helm-controller/blob/b91fd90c75b80238cf20105f2c4a6b8294bde904/api/v2/helmrelease_types.go#L366

## Reference Implementations

- ArgoCD Issue (already implemented): https://github.com/argoproj/argo-cd/issues/18634
- ArgoCD Docs: https://argo-cd.readthedocs.io/en/latest/user-guide/kustomize/#components

## Current Behavior

Kustomization (build) fails due to not finding the component. Behavior not changeable.

## Expected Behavior

Kustomization (build) fails due to not finding the component if `ignoreMissingComponents` isn't set / is set to false. If set to true, it will check if the directory exists prior to building the kustomization and if it doesn't exist, it will simply leave it out.

## Technical Implementation

In the [components for loop here](https://github.com/fluxcd/pkg/blob/main/kustomize/kustomize_generator.go#L215), check if `ignoreMissingComponents` is set to true. If it is, check if the directory is existent, if it isn't, just `continue`.

I would also be interested in implementing this if this is an acceptable feature :)
