### ISSUE TITLE
Issue with validation of Helm Release

### ISSUE THREAD

**Issue by frank-bee** [fluxcd/kustomize-controller#1443]
I get the following error from the kustomize controler 
```
HelmRelease/tdp/tdp-api dry-run failed (Invalid): HelmRelease.helm.toolkit.fluxcd.io "tdp-api" is invalid: [spec.chart.spec.chart: Required value, spec.chart.spec.sourceRef: Required value, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
```

My resources 
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: technical-details-parser-api
  namespace: tdp
spec:
  interval: 5m
  url: oci://foo.azurecr.io/helm-charts/bar
  provider: azure
  ref:
    semver: ">=0.1.0-0"  # Includes prereleases (e.g., 0.1.0-655718e)
    semverFilter: ".*-.*"  # Matches tags with hyphens (e.g., commit hashes)
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdp-api
  namespace: tdp
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: technical-details-parser-api
    namespace: tdp
```

My setup:
```                                
flux: v2.5.1
distribution: flux-v2.5.1
helm-controller: v1.2.0
kustomize-controller: v1.5.1
notification-controller: v1.5.0
source-controller: v1.5.0

```
