### ISSUE TITLE
Controller-level decryption for Age Keys

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/kustomize-controller#1465]
We currently support [controller-level decryption](https://fluxcd.io/flux/components/kustomize/kustomizations/#controller-global-decryption) for KMS services only. We should extend the SOPS integration and allow cluster-admins to configure controller-level decryption with static Age keys as well. 

We can add a controller flag `--sops-age-secret=<name>` that allows cluster-admins to point kustomize-controller to a Kubernetes Secret that contains the Age keys. The secret must be in the same namespace as kustomize-controller and must contain keys in the format:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: sops-keys
  namespace: flux-system
stringData:
  identity1.agekey: <identity1 key>
  identity2.agekey: <identity1 key>
```

When the `--sops-age-secret` flag is set, in the `Decryptor.ImportKeys()` we'll read the Kubernetes Secret and load the keys, we must do this every time and not cache the Age keys since they can change at any time.
