### ISSUE TITLE
Allow kustomize image override in Kustomization CRD

### ISSUE THREAD

**Issue by SomtochiAma** [fluxcd/kustomize-controller#193]
In a case where the person with control over the syncing(kustomization CRD) does not have control over the config repository where the `kustomization.yml` reside and they can only refer to it. It would be great want to allow making changes(overriding the images) in the Kustomization CRD

Link to discussion:
(https://github.com/fluxcd/flux2/discussions/135)[https://github.com/fluxcd/flux2/discussions/135]
In particular this comment
> In the first, the person with control over the syncing does not have control over the config repository -- they can only refer to it. So they must resort to putting changes into the sync.

**Comment by stefanprodan** [comment]
Here is an example that could be used in e2e testing.

Having a public repo and a kustomization for podinfo:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  path: "./kustomize"
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client
```

I want to change the podinfo image tag without modifying podinfo repo, to do that I can override the image with:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  path: "./kustomize"
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client
  images:
    - name: ghcr.io/stefanprodan/podinfo
      newName: ghcr.io/stefanprodan/podinfo
      newTag: 5.0.0
```
