### ISSUE TITLE
Is it me or this use a different version of kubectl than flux V1.x? (Force Bases instead of usage of resources)

### ISSUE THREAD

**Issue by Nordes** [fluxcd/kustomize-controller#208]
Hi, in Flux V1.x I had no issue with my Kustomization yaml files. However, after upgrading to Flux2 with this kustomize-controller, it seems that my files are not valid anymore. Basically, if I keep the content only in `resources` it fails silently and flux juste delete itself after installing. However if I use the `bases` instead of `resources` it works as expected.

In the documentation of Kuztomize (https://kubectl.docs.kubernetes.io/references/kustomize/bases/) we can read the following:
> The bases field was deprecated in v2.1.0

**My files were like this (Fail in Flux2, works in Flux v1):**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flux-system
- some-folder
```

**And I had to make the changes to:**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- flux-system
- some-folder
```

**System information:**
K8s Version: 1.18.10
Kustomize-controller: 0.5.4

(If more details is needed, I will give them)
