### ISSUE TITLE
Health check event is emitted in every reconciliation cycle

### ISSUE THREAD

**Issue by bergemalm** [fluxcd/kustomize-controller#236]
Hi,

With merge of #219 the "health check passed"-event/notification is emitted in every reconciliation cycle for all Kustomizations always.

https://github.com/fluxcd/kustomize-controller/blob/5356194f5a2791af0d14c0b2f429e653f7440065/controllers/kustomization_controller.go#L699
`ready` will always be false since `readiness.Status` will be `Unknown` at the stage of checkHealth.

```
.
.
Status:
  Conditions:
    Last Transition Time:   2021-01-13T08:38:10Z
    Message:                reconciliation in progress
    Reason:                 Progressing
    Status:                 Unknown
    Type:                   Ready
.
.
```
Status is updated later in the reconciliation cycle.
https://github.com/fluxcd/kustomize-controller/blob/5356194f5a2791af0d14c0b2f429e653f7440065/controllers/kustomization_controller.go#L385

Am I missing something?

Example of `kind: Kustomization` used:

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 15m
  path: ./mgmt/namespaces/my-namespace/my-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: my-app
      namespace: my-namespace
  timeout: 5m
  validation: client
```
