### ISSUE TITLE
Variable substitution failed: missing closing brace when using variable substitution in Kustomization

### ISSUE THREAD

**Issue by ilya-git** [fluxcd/kustomize-controller#290]
### Describe the bug

I have set up a simple variable substitution as described in the documentation from config map:

```
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: env-config
```

Then I use it in helm release values:

```
values:
   secrets:
      userAssignedIdentityID: "${kubelet-identity-client-id}"
```

`kubectl get configmap`

```
apiVersion: v1
data:
  ...
  kubelet-identity-client-id: <a guid in here>
kind: ConfigMap
```

When Kustomization controller runs, I get the following error:

`var substitution failed for 'my-app': variable substitution failed: missing closing brace`

If I write a random name (var does not exist in config map) instead of `kubelet-identity-client-id`, then an empty string is written.

### Expected behavior

No error or another error that describes what is the problem (the closing brace seems to be in place at least right now)

### Additional context

- Kubernetes version: 1.20.2
- Git provider: Bitbucket
- Container registry provider: Azure Container Registry

Below please provide the output of the following commands:

```cli
flux --version: 0.8.2
flux check

► checking prerequisites
✗ flux 0.8.2 <0.9.0 (new version is available, please upgrade)
✔ kubectl 1.20.0 >=1.18.0-0
✔ Kubernetes 1.20.2 >=1.16.0-0
► checking controllers
✔ helm-controller: healthy
► ghcr.io/fluxcd/helm-controller:v0.7.0
✔ kustomize-controller: healthy
► ghcr.io/fluxcd/kustomize-controller:v0.8.1
✔ notification-controller: healthy
► ghcr.io/fluxcd/notification-controller:v0.8.0
✔ source-controller: healthy
► ghcr.io/fluxcd/source-controller:v0.8.1
✔ all checks passed
```

**Comment by pmialon** [comment]
Hi, 

I have a similar problem, I generate ConfigMap in my kustomization.

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - application.yml=app-conf
    name: app-conf

```

but the file app-conf contain [spring placeholders](https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-placeholders-in-properties) like this : 

```
app.name=MyApp
app.description=${app.name} is a Spring Boot application
```

I have the same error message: 
```var substitution failed for 'my-app': variable substitution failed: missing closing brace```

The only way I found is to entirely disable envsubst for this configmap. 

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - application.yml=app-conf
    name: app-conf
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
```

**Comment by xvzf** [comment]
@pmialon did you find a solution?

**Comment by Tzrlk** [comment]
From the [docs](https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution): 
> Note that if you want to avoid var substitutions in scripts embedded in ConfigMaps or container commands, you must use the format $var instead of ${var}. If you want to keep the curly braces you can use $${var} which will print out ${var}.

**Comment by old-guy-coder** [comment]
I know this is an old ticket but I am facing a similar problem, I am creating a config map using configMapGenerator in a Kustomization which is triggered by a Flux Kustomization called `k8s-infrastructure-configs`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: infrastructure
configMapGenerator:
  - name: environment-release-values
    namespace: flux-system
    files:
      - environment=../../config/environment-values.yaml
  - name: geography-release-values
    namespace: flux-system
    files:
      - geography=../../config/eu/geography-values.yaml
```

The format of the geography-values.yaml is:

```yaml
adxClusterName: ""
adxClusterUri: ""
adxDatabaseName: ""
adxLogsMigratorClientIdName: ""
adxLogsMigratorClientSecretName: ""
adxLogsReaderClientIdName: ""
adxLogsReaderClientSecretName: ""
applicationInsightsConnectionStringSecretName: ###
applicationInsightsInstrumentationKeySecretName: ###
applicationInsightsName: ###
asoWorkloadIdentityClientId: ###
asoWorkloadIdentityTenantId: ###
logAnalyticsWorkspaceName: ###
monitoringActionGroupId: ###
name: ###
primaryRegion: uksouth
prometheusQueryEndpoint: ###
prometheusQueryEndpointClientId: ###
prometheusQueryEndpointClientSecret: ###
regionNames:
- uksouth
resourceGroupName: ###
serviceBusConnectionStringSecretName: ###
serviceBusName: ###
```

and the resulting config map looks like this:

```yaml
apiVersion: v1
data:
  geography: |
    adxClusterName: ""
    adxClusterUri: ""
    adxDatabaseName: ""
    adxLogsMigratorClientIdName: ""
    adxLogsMigratorClientSecretName: ""
    adxLogsReaderClientIdName: ""
    adxLogsReaderClientSecretName: ""
    applicationInsightsConnectionStringSecretName: ###
    applicationInsightsInstrumentationKeySecretName: ###
    applicationInsightsName: ###
    asoWorkloadIdentityClientId: ###
    asoWorkloadIdentityTenantId: ###
    logAnalyticsWorkspaceName: ###
    monitoringActionGroupId: ###
    name: ###
    primaryRegion: uksouth
    prometheusQueryEndpoint: ###
    prometheusQueryEndpointClientId: ###
    prometheusQueryEndpointClientSecret: ###
    regionNames:
    - uksouth
    resourceGroupName: ###
    serviceBusConnectionStringSecretName: ###
    serviceBusName: ###
kind: ConfigMap
```

Now, I have another Flux Kustomization that depends on the `k8s-infrastructure-configs` which I am trying to do a postBuild substitution from the config map defined above on a resource created by this config map and getting the same error message, in the resource I want to pick a few of the variables from the config map for replacement, e.g.

```yaml
apiVersion: alertsmanagement.azure.com/v1api20230301
kind: PrometheusRuleGroup
metadata:
  name: flux-suspended-hr
  namespace: flux-system
spec:
  location: ${geography.primaryRegion}
  // omitted for brevity
```

Note the variable referred to above should map to the same variable from the config map as `primaryRegion` is nested under `geography` but no matter what I try (`${geograhpy_primaryRegion}`, `${geography\\primaryRegion}`, `${geography/primaryRegion}`, `${geography["primaryRegion"]}`) I am getting this same error, is what I am trying to do even possible? If I just enter `${geography}` then I get a different error which talks about JsonToYaml conversion so it certainly looks like the values are getting picked up but I do not seem to be able to select the nested value.

Any help with this would be greatly valued.
