### ISSUE TITLE
Variable substitution replaces all variables, defined or not

### ISSUE THREAD

**Issue by nomeelnoj** [fluxcd/kustomize-controller#297]
When using the kustomize variable substitution with `envsubst`, kustomize will replace values as empty if they are not defined, which might be on purpose.  Using the substitution to set some values but not others can break workloads, including the example cronjob to sync ecr credentials:

```
# kustomization
  ...
  postBuild:
    substitute:
      cluster_env: dev
```
But then the workload that should have the following command:
```
- command:
  - /bin/sh
  - -ce
  - aws ecr get-login-password --region ${REGION} > /token/ecr-token
  env:
  - name: REGION
    value: us-east-1
```
ends up being created in the cluster as:
```
- command:
  - /bin/sh
  - -ce
  - aws ecr get-login-password --region > /token/ecr-token
  env:
  - name: REGION
    value: us-east-1
```
