### ISSUE TITLE
Checksum label is missing when prune is false

### ISSUE THREAD

**Issue by stealthybox** [fluxcd/kustomize-controller#305]
When prune is true, child objects of Kustomizations have these labels:
```
labels:
  kustomize.toolkit.fluxcd.io/checksum: 21ff4959f5c2052e702115c585ea8cf694c67613
  kustomize.toolkit.fluxcd.io/name: flux-system
  kustomize.toolkit.fluxcd.io/namespace: flux-system
```
When you set prune to false, the checksum label is dropped:
```
labels:
  kustomize.toolkit.fluxcd.io/name: flux-system
  kustomize.toolkit.fluxcd.io/namespace: flux-system
```

Even if the user does not have garbage collection enabled, it is still very useful to have these checksum labels because you can use them to identify stale resources.
This would for example be useful in a `flux tree` view or a web interface like the Flux UI that shows which objects are managed and which are not.

I don't see any reason not to include these checksums.
It should be a relatively safe change for existing Kustomizations when kustomize-controller is updated, but it will cause every object to be patched with new labels.
