### ISSUE TITLE
Deleting a default key for helmrelease (setting to null)

### ISSUE THREAD

**Issue by messiahUA** [fluxcd/kustomize-controller#372]
Helm supports unsetting/deleting the default chart value: https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key

It works as expected when you set some value to null when HelmRelease is created the first time, for example you set cpu limit to null and the end result is:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
[...]
spec:
  values:
    resources:
      limits:
        cpu: null
        memory: 128Mi
```

but if you update the HelmRelease and set some other value to null, for example memory limit, it ends up as:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
[...]
spec:
  values:
    resources:
      limits:
        cpu: null
```

Thus, it doesn't propagate to helm and has no effect at all. I hope this bug is not an inherent for the kubectl/k8s itself and can be fixed in kustomize-controller.

**Comment by stefanprodan** [comment]
I guess this is what `kustomize build` does too, in Flux we don’t manipulate yaml directly, we use the kustomize/api package to build the yamls in the same way the kustomize CLI does it.

**Comment by messiahUA** [comment]
@stefanprodan I've just tested by running kustomize build locally - it produces the value with null correctly and as I've mentioned it works as expected when the resource is created the first time. The problem occurs only on update.

Actually, I've just tested this manually by executing kubectl apply in the same order (result is the same), so this is related to kubectl and how it applies the change...

**Comment by stefanprodan** [comment]
> so this is related to kubectl and how it applies the change

I don't see how we could do something about this, we exec to run `kubectl apply` and it's up to kubectl to do the 3-way-merge.

**Comment by messiahUA** [comment]
`kubectl apply --server-side=true` works correctly in my simple test, but it causes a conflict with helm-controller managed field.

**Comment by kingdonb** [comment]
Should this be moved to Helm Controller? I'm not sure it is a Kustomize Controller issue.

**Comment by messiahUA** [comment]
I think that this is indeed not a kustomize controller issue and not even a fluxcd issue, but if there are any ideas on the solution then can be moved to helm controller for sure.

In any case the good workaround is to just move the values to configmap and reference it via valuesFrom.

**Comment by gberche-orange** [comment]
> Does it mean that Flux does not handle this special `null` value as Helm describes in [deleting-a-default-key](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key)?

I'm reproducing the same problem with https://github.com/crossplane/crossplane/blob/969b8ebdf2aedc1849302b687f2eebeba94b55f3/cluster/charts/crossplane/values.yaml.tmpl#L65-L69

whose value.yml has 
```
securityContextCrossplane:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
```

A strategic patch with the following 
```
spec:
  values:
    #see https://github.com/jeremycaine/crossplane-with-openshift/blob/main/1.%20Installing%20Crossplane%20on%20Openshift/README.md#install-crossplane
    securityContextCrossplane:
      runAsUser: null
      runAsGroup: null
    securityContextRBACManager:
      runAsUser: null
      runAsGroup: null 
```

when trying to set a null runAsUser in the value gets ignored, and results into the HelmRelease value field as 

``` 
    securityContextCrossplane: {}
    securityContextRBACManager: {}
```

As a result the default chart values are assigned by flux helm release

```
       securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsUser: 65532
```

Trying to assign an empty map {} in the value, simply gets ignored by the strategic merge.

My workaround is to use helm post rendered to correct incorrect helm values in the resulting helm rendered templates, but this breaks the helm chart encapsulation.
