### ISSUE TITLE
Kustomization marked as ready when health check resource is not ready

### ISSUE THREAD

**Issue by makkes** [fluxcd/kustomize-controller#387]
I'm observing kustomize-controller marking a Kustomization resources as `Ready` under the following circumstances:

1. The health checks for the Kustomization are configured like this:
    ```
    healthChecks:
      - apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        name: any
        namespace: flux-system
    ```
2. helm-controller hasn't started reconciling the `any` HelmRelease so that it has no status field. This is easy to reproduce by scaling the helm-controller deployment down to 0 replicas.

I've seen this happen on cluster with heavy load so that the helm-controller hasn't started reconciling the `any` HelmRelease, yet.

The reason for this is that kstatus reports the HelmRelease as Current, even though it is actually not.

This is problematic in the case where other Kustomizations depend on a Kustomization that has health checks for resources that expose a proper kstatus-compatible API (like status field, observedGeneration etc.) because the dependencies would be applied even though the health checks for the original Kustomization they depend on would get un-ready at a later stage (e.g. due to the HelmRelease not being ready, yet).
