### ISSUE TITLE
kustomization.yaml with no resources fails

### ISSUE THREAD

**Issue by makkes** [fluxcd/kustomize-controller#391]
Given this kustomization file in a directory pointed to by a Flux Kustomization:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
```

The Kustomization fails with this error:
```sh
$ k -n flux-system get kustomization k
NAME   READY   STATUS   AGE
k      False   apply failed: error: no objects passed to apply
       39s
```
which makes sense because there are no resources to apply but I wonder whether a check should be added to kustomize-controller to see whether the set of resources is actually empty and immediately go into ready state. Happy to discuss.
