### ISSUE TITLE
Inline patchesStrategicMerge patch fails with no such file or directory

### ISSUE THREAD

**Issue by bramk** [fluxcd/kustomize-controller#393]
I am trying to use an inline patch in below kustomization, but when I apply it  the controller seems to treat it as a filename and result in "no such file or directory". (flux version 0.16.1).  The inline patch does work when I specifiy it as part of a regular `kustomization.yaml` and run a local build. Am I doing something wrong or is this not (yet) supported by the controller?

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cluster-autoscaler
  patchesStrategicMerge:
    - |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: cluster-autoscaler
      spec:
        values:
          awsRegion: eu-west-1
          autoDiscovery:
            clusterName: mycluster
  prune: true
  validation: client
```
Logs
```
{"level":"error","ts":"2021-07-21T11:41:19.748Z","logger":"controller.kustomization","msg":"Reconciliation failed after 58.056496ms, next try in 10m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"cluster-autoscaler","namespace":"flux-system","revision":"main/d14e74a8399d7867e82e8ac7e46e1c237ecff037","error":"kustomize build failed: trouble configuring builtin PatchStrategicMergeTransformer with config: `\npaths:\n- '\"apiVersion: helm.toolkit.fluxcd.io/v2beta1\\nkind: HelmRelease\\nmetadata:\\n  name:\n  cluster-autoscaler\\nspec:\\n  values:\\n    awsRegion: eu-west-1\\n    autoDiscovery:\\n      clusterName:\n  eks-ig-infra2\"'\n`: open /tmp/cluster-autoscaler913889667/infrastructure/cluster-autoscaler/\"apiVersion: helm.toolkit.fluxcd.io/v2beta1\\nkind: HelmRelease\\nmetadata:\\n  name: cluster-autoscaler\\nspec:\\n  values:\\n    awsRegion: eu-west-1\\n    autoDiscovery:\\n      clusterName: mycluster\": no such file or directory"}
```

**Comment by JaneLiuL** [comment]
Hi , kustomize-controller support the patchesStrategicMerge, and the format should be as below, would you correct your format and try again ? @bramk 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  patchesStrategicMerge:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: podinfo
    spec:
      template:
        spec:
          serviceAccount: custom-service-account
```
