### ISSUE TITLE
Kustomization on a single file

### ISSUE THREAD

**Issue by Zempashi** [fluxcd/kustomize-controller#418]
I would like to apply a single file as a kustomization prior to install the entire directory in another kustomization later.
I do this for dependency management and breaking what could possibly a circular dependency between two components (components needed to run prometheus monitoring that are also monitored afterwards, but that need to push grafana dashboard in the monitoring namespace before the prometheus stack is actually installed)

Applying something like:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-namespace
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-infra/kube-monitoring/kube-prometheus-stack/namespace.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
```

will result in a error:
```
prometheus-namespace    False   kustomize create failed: open /tmp/prometheus-namespace204362313/flux-infra/kube-monitoring/kube-prometheus-stack/namespace.yaml/kustomization.yaml: not a directory
```

The work around is quite simple : put the namespace.yml in a separated directory, but for a simple file like that I would like it to stand close to other related configs (helm-repository.yml and helm-release.yml for kube-prometheus-stack)
