### ISSUE TITLE
How does prune work in detail?

### ISSUE THREAD

**Issue by mstoetzer** [fluxcd/kustomize-controller#428]
Given the following config:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: foobar-dev
spec:
  interval: 5m0s
  path: ./dev
  prune: true
```

The directory structure in the repo looks like the following:

```yaml
cool-repo-name
  |- dev/
  |- not-applied-by-fluxcd/
```

So the Kustomization controller is configured to watch for file inside the `dev` directory. Also it should `prune` manifests when they are not there anymore.

What happens, when I move some manifests from the `dev` directory to the `not-applied-by-fluxcd` directory? Will FluxCD delete these manifests from the cluster?
