### ISSUE TITLE
Post-build substitution can mess up output

### ISSUE THREAD

**Issue by wolfmah** [fluxcd/kustomize-controller#437]
I was in the process of creating a CronJob, in our Flux 2 workflow, and got hit by a weird behavior. At first, I had to put the annotation `kustomize.toolkit.fluxcd.io/substitute: disabled`, otherwise, what was found inside the `command` action was not executable. I dug deeper to find the cause and here's what I found.

Here is a full simple CronJob with the faulty behavior (I will not repeat the complete manifest for subsequent examples). A thing to note is the usage of multi-line as well as the extra space at the end of the `command`.
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-multiline-space
  namespace: default
spec:
  suspend: false
  schedule: 0 */6 * * *
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: debian:latest
              name: test
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -ce
                - |-
                  a \
                    -b c 
```

When parsed through `kustomize build`, this result in a command that look like thi:
```
> kustomize build test | yq eval '. | select(.metadata.name == "test-multiline-*space") | .spec.jobTemplate.spec.template.spec.containers[0]' -

command:
  - /bin/bash
  - -ce
  - "a \\\n  -b c "
```

When adding substitution into the mix (via `drone/envsubst`), the output changes to this:
```
> kustomize build test | $GOPATH/bin/envsubst | yq eval '. | select(.metadata.name == "test-multiline-*space") | .spec.jobTemplate.spec.template.spec.containers[0]' -

command:
  - /bin/bash
  - -ce
  - "a \\n  -b c "
```

If you didn't saw the difference, there's a backslash missing.

I really don't know why this behavior occurs when activating `envsubst`. Disabling substitution via the annotation allows the YAML to be recognize correctly by Kubernetes (with the triple backslash). On the other hand, removing the trailing whitespace changes the Kustomize output considerably, which doesn't get affected by substitution:

```
# manifest
...
              command:
                - /bin/bash
                - -ce
                - |-
                  a \
                    -b c

# kustomize output
command:
  - /bin/bash
  - -ce
  - |-
    a \
      -b c

# kustomize + envsubst output
command:
  - /bin/bash
  - -ce
  - |-
    a \
      -b c
```

### Expected behavior

When there an extra space at the end of a multi-line string, Flux's substitution shouldn't remove any char from the string, but simply replace vars found within `${}`.

Of course, the easy fix is to not add the extra space. And there's a workaround with the annotation that disable the substitution. But if both are not met, Flux's substitution will silently mangle up the manifest.
