### ISSUE TITLE
Same variables from multiple secrets defined in substituteFrom should use the last value in the array

### ISSUE THREAD

**Issue by ruzickap** [fluxcd/kustomize-controller#438]
I'm creating this issue based on "comment" in discussion: https://github.com/fluxcd/flux2/discussions/1875

In case of using multiple Secrets in substituteFrom the values should be merged based on position in the array.

Example: 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: group-apps-substitutefrom-secret
  namespace: flux-system
data:
  MY_EMAIL: my_group_base64_encoded_email       ## <- Value should not be used
  GROUP_VARIABLE: base64_encoded_text
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cluster-apps-substitutefrom-secret
  namespace: flux-system
data:
  MY_EMAIL: my_cluster_base64_encoded_email     ## <- Value should be used     
  CLUSTER_VARIABLE: base64_encoded_text
```

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
...
path: ./groups/dev/group-apps/apps
...
spec:
  postBuild:
    substituteFrom:
    - kind: Secret
      name: group-apps-substitutefrom-secret
    - kind: Secret
      name: cluster-apps-substitutefrom-secret  ## <- Values `MY_EMAIL` from this secret should be used 
...
```

```yaml
# "groups/dev/group-apps/apps/test.yaml"
...
spec:
  email: ${MY_EMAIL}
  variable_cluster: ${CLUSTER_VARIABLE}
  variable_group: ${GROUP_VARIABLE}
...
```

The final output generated by Flux (`groups/dev/group-apps/apps/test.yaml`) is currently looking 

```yaml
spec:
  MY_EMAIL: my_cluster_base64_encoded_email    ## <- this variable should be taken from the "cluster-apps-substitutefrom-secret" Secret and should be "my_cluster_base64_encoded_email"
  CLUSTER_VARIABLE: base64_encoded_text
  GROUP_VARIABLE: base64_encoded_text
``` 

It means - Flux is currently using value `MY_EMAIL` from first "secret array field" `group-apps-substitutefrom-secret` and not the value from the last one `cluster-apps-substitutefrom-secret`.

The output should look like:

```yaml
spec:
  MY_EMAIL: my_cluster_base64_encoded_email
  CLUSTER_VARIABLE: base64_encoded_text
  GROUP_VARIABLE: base64_encoded_text
``` 

Let me know if this make sense and it is understandable...
