### ISSUE TITLE
Upgrade from v0.17.2 to v0.18.0 causes changes on each reconcile cycle

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/kustomize-controller#450]
Before the upgrade we only got events on slack when there was in fact changes checked into git, after the upgrade we get events on every 10mins:
```
CustomResourceDefinition/volumesnapshots.snapshot.storage.k8s.io configured
Secret/flux-system/slack-url configured
```

The slack-url is a sops encrypted secret

**Comment by davidkarlsen** [comment]
there's no creationTimestamp in it.

**Comment by bergemalm** [comment]
@stefanprodan kubernetes GKE version `v1.20.9-gke.1001`. This secret is a certificate, not encrypted.

```
apiVersion: v1
kind: Secret
data:
  my.ca: <base64 encoded data>
metadata:
  creationTimestamp: null <---- line removed
  name: my-tls
  namespace: service-namespace
```
