### ISSUE TITLE
error: failed to create typed patch object: .status.loadBalancer: field not declared in schema

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/kustomize-controller#453]
going from kustomize controller v0.15.1 to v0.15.2 or v0.15.3 now this fail:
```
Service/devops/ocp-project-admin dry-run failed, error: failed to create typed patch object: .status.loadBalancer: field not declared in schema
revision
os-cts/d0ea0091642b731281c9ee8bcddee83ff78c08d1
```

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ocp-project-admin
  namespace: devops
spec:
  template:
    spec:
      serviceAccountname: ocp-project-admin
      containers:
```
