### ISSUE TITLE
HPA v2beta1 error: .spec.metrics[0].resource.target: field not declared in schema

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/kustomize-controller#454]
kustomize-controller v0.15 can't reconcile HPA manifests of version `autoscaling/v2beta1`

```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
  name: opentelemetry-collector
  namespace: some-ns
spec:
  maxReplicas: 6
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentelemetry-collector
```

error:
```
HorizontalPodAutoscaler/some-ns/opentelemetry-collector dry-run failed, error: failed to create typed patch object: errors:
 .spec.metrics[0].resource.target: field not declared in schema
 .spec.metrics[1].resource.target: field not declared in schema
```
