### ISSUE TITLE
Implicit empty "target" in patch breaks Kustomize strategic merge logic

### ISSUE THREAD

**Issue by artem-nefedov** [fluxcd/kustomize-controller#464]
### Describe the bug

When using "patches" directive in Kustomization manifest, if "target" is not specified for a specific patch, it's added implicitly as `target: {}`. The problem is that it breaks strategic merge logic, because Kustomize allows for strategic merge patches to have no target, but any existing target (even an empty one) changes behavior.

Suppose you have the following "ns.yaml" manifest:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: v1
kind: Namespace
metadata:
  name: bar
```

And the following "kustomization.yaml":

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns.yaml

patches:
- patch: |
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: bar
```

This patch will delete namespace only "bar". But if we add empty `target: {}` to this patch, it will delete everything!
This is reproduced with local kustomize, and the same thing happens with Kustomization applied by controller. 

### Steps to reproduce

Make Kustomization manifest with "patches" section, and specify a strategic merge patch with no "target" section.

### Expected behavior

Patch is passed as-is to kustomize, with no target added.

### OS / Distro

N/A

### Flux version

0.18.3

### Flux check

✔ kubectl 1.21.3 >=1.18.0-0
✔ Kubernetes 1.21.2-eks-0389ca3 >=1.16.0-0
► private-repo/fluxcd/helm-controller:v0.12.0
► private-repo/fluxcd/kustomize-controller:v0.15.5
► private-repo/fluxcd/notification-controller:v0.17.1
► private-repo/fluxcd/source-controller:v0.16.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
