### ISSUE TITLE
Cluster scope objects are marked as namespaced

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/kustomize-controller#466]
The Kustomize namespace transformer adds `metadata.namespace` to custom resources irregardless of their scope (namespace or cluster). When such a transformer is used (e.g. `.spec.targetNamespace`) the kustomize-controller inventory records the cluster scoped objects as namespaced. 

When cluster scope objects have `metadata.namespace`, health checking  (`.spec.wait`) fails like so:
```
Health check failed after 4m30.008625477s, timeout waiting for: [ClusterIssuer/some-ns/issuer-1 status: ‘Unknown’, ClusterIssuer/some-ns/issuer-2 status: ‘Unknown’, KongClusterPlugin/some-ns/prometheus-global status: ‘Unknown’]
```

**Comment by takirala** [comment]
I am seeing this in flux 0.22.1 (i think kustomize-controller 0.18.0):

```
status:
  conditions:
  - lastTransitionTime: "2021-11-16T18:27:13Z"
    message: 'timeout waiting for: [Namespace/catalog-project status: ''Unknown'':
      context deadline exceeded]'
    reason: ReconciliationFailed
    status: "False"
    type: Ready
  inventory:
```

I tested the kustomization with and without `spec.targetNamespace` and still got the same error. 
I tested the kustomization with and without `spec.serviceAccountName` and still got the same error. 

**Note** that I have created the namespace even before flux is installed. So flux did not create the namespace but just merely tried to sync the ns manifest.
