### ISSUE TITLE
endless reconciles of namespaceconfig CR

### ISSUE THREAD

**Issue by davidkarlsen** [fluxcd/kustomize-controller#471]
We use this https://github.com/redhat-cop/namespace-configuration-operator with this CR:

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: resource-quota-small
spec:
  labelSelector:
    matchLabels:
      fss.tietoevry.com/resource-quota: small
  templates:
  - objectTemplate: |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: compute-resources
        namespace: {{ .Name }}
        labels:
          app.kubernetes.io/managed-by: namespace-configuration-operator
      spec:
        hard:
          requests.cpu: "2"
          requests.memory: 4Gi
          limits.cpu: "6"
          limits.memory: 4Gi
```

but the kustomize controller seems to apply it on each run, causing notifications every 10mins.
Running flux v0.19.0
