### ISSUE TITLE
Getting an error when reconciling kustomization, even though all related HelmReleases were reconciled succesfully

### ISSUE THREAD

**Issue by fernandocamargoai** [fluxcd/kustomize-controller#473]
I have a cluster that has been active for some months. I noticed that something happened recently that for some reason flux couldn't authenticate with the GitRepository. I ended up deleting the Deploy Key, the flux-system secret, and running bootstrap again and it solved my problem. I also upgraded my flux cli and decided to upgrade the components as well. Then, I had a problem in which one of my HelmReleases was stuck with this error: https://github.com/fluxcd/helm-controller/issues/149. I followed instructions I found in the comments, rollbacked the HelmRelease and tried to reconcile again. Then, I got to the current problem:

```bash
✗ Kustomization reconciliation failed: HelmRelease/ambassador namespace not specified, error: the server could not find the requested resource (patch helmreleases.helm.toolkit.fluxcd.io ambassador)
```

Since the first part talks about namespace, I thought it could be because the `ambassador` namespace is part of the HelmRelease and it was getting messed up somethow. So, I moved the namespace definition to another kustomatization that runs before the one that includes this HelmRelease. It didn't solve the problem.

So, I started looking at the second part of the message and found two issues: https://github.com/fluxcd/flux/issues/2326 and https://github.com/fluxcd/flux/issues/2561. I checked the CRD in the cluster and the version is correct: v2beta1. But to be sure, I applied the CRDs again just to make sure:

```bash
kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-controller/main/config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml
```

I tried reconciling again and the problem persists.

Some possible useful outputs:

```bash
$ flux version
flux: v0.19.1
helm-controller: v0.12.1
image-automation-controller: v0.15.0
image-reflector-controller: v0.13.0
kustomize-controller: v0.16.0
notification-controller: v0.18.1
source-controller: v0.16.1
```

```bash
$ flux get helmreleases --all-namespaces
NAMESPACE       NAME                            READY   MESSAGE                                 REVISION        SUSPENDED 
default         ambassador                      True    Release reconciliation succeeded        6.7.13          False    
default         prometheus-stack                True    Release reconciliation succeeded        19.2.2          False    
default         redis                           True    Release reconciliation succeeded        14.0.2          False    
default         seldon-core                     True    Release reconciliation succeeded        1.11.2          False    
default         similar-product-recommender     True    Release reconciliation succeeded        0.4.13          False
```

```bash
$ flux get kustomizations 
NAME            READY   MESSAGE                                                                                                                                                         REVISION                                     SUSPENDED 
apps            False   dependency 'flux-system/infrastructure' is not ready                                                                                                            main/980b373cd62e7dbeb26f83ad1d2be024458428d5False    
configs         True    Applied revision: main/70a0bc1ac91cbefed41dda7e5134c83262870b04                                                                                                 main/70a0bc1ac91cbefed41dda7e5134c83262870b04False    
flux-system     True    Applied revision: main/70a0bc1ac91cbefed41dda7e5134c83262870b04                                                                                                 main/70a0bc1ac91cbefed41dda7e5134c83262870b04False    
infrastructure  False   HelmRelease/ambassador namespace not specified, error: the server could not find the requested resource (patch helmreleases.helm.toolkit.fluxcd.io ambassador)  main/980b373cd62e7dbeb26f83ad1d2be024458428d5False
```

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ambassador
spec:
  releaseName: ambassador
  chart:
    spec:
      chart: ambassador
      version: "6.7.x"
      sourceRef:
        kind: HelmRepository
        name: datawire
        namespace: flux-system
  interval: 1h0m0s
  targetNamespace: ambassador
  values:
    image:
      repository: docker.io/datawire/ambassador
    enableAES: false
    crds:
      keep: false
    service:
      type: NodePort
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      annotations:
        cloud.google.com/backend-config: '{"default": "ambassador-hc-config"}'
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi
  valuesFrom:
    - kind: ConfigMap
      name: cluster
      valuesKey: ambassador_replicas
      targetPath: replicaCount
```
