### ISSUE TITLE
"Dependencies do not meet ready condition" is a bit spammy

### ISSUE THREAD

**Issue by CitadelCore** [fluxcd/kustomize-controller#492]
With a long dependsOn chain (3+) and event notifications set up, there is a lot of `Dependencies do not meet ready condition` noise, especially when there's a short re-check interval set.

**Comment by uderik** [comment]
any updates ?

**Comment by somtochiama** [comment]
In the Alert, you can filter out certain events using `spec,exclustionList`

**Comment by uderik** [comment]
@somtochiama if I want to receive this notifications, but I don't want to receive them when there are no problems?

**Comment by somtochiama** [comment]
>  I don't want to receive them when there are no problems
Can you explain further what you mean?
The message itself indicates that there is a problem. A dependency is ready so the kustomization isn't being applied.

**Comment by gavinclarkeuk** [comment]
We've got a set of 7 kustomizations that depend on each other sequentially, and are set to reconcile every 10mins, and we see these message regularly when nothing is wrong. There isn't a specific pattern but we'll typically get notifications every couple of hours. This will happen when there have been no changes to the git repository or the resources, it is just happening because one of the earlier kustomizations is being reconciled so isn't in a Ready state.

If there is a genuine problem then the health checks will fail and we get a separate error notification from the relevant kustomization.

I haven't looked at the code but my feeling is that the only "problem" here is one or more of the following:
- the reconciliations aren't happening quickly enough
- reconciliations are waiting long enough for dependencies before sending a message
- the reconciliation ordering isn't being smart about the dependency tree.

Given there are no actual changes I'd imagine you could reconcile the whole dependency tree together in minimal time, but I assume each kustomization is being reconciled on it's own schedule and they can therefore drift in a way that means the reconciliations overlap in a way that causes this noise

**Comment by gavinclarkeuk** [comment]
I guess one possible workaround might be to set the `--concurrent` flag to `1`, but that probably isn't suitable for all use cases

**Comment by stefanprodan** [comment]
The "Dependencies do not meet ready condition" events can be safely dropped as any reconcile errors will be reported separately. To drop the events use:

```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-system
  namespace: flux-system
spec:
  providerRef: 
    name: on-call-slack
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
  exclusionList:
    - "^Dependencies.*"
```
