### ISSUE TITLE
HorizontalPodAutoscaler causes repeated "configured" logs in kustomize log

### ISSUE THREAD

**Issue by Legion2** [fluxcd/kustomize-controller#494]
I have two HorizontalPodAutoscaler reconciled by a Kustomization. They both are created as expected by the Kustomization, however the follwoing is shown in the events of the Kustomization:
```
Normal  info  2m40s (x542 over 4d3h)  kustomize-controller  HorizontalPodAutoscaler/foo/hpa configured HorizontalPodAutoscaler/bar/hpa configured
```

This is the resource yaml:
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 3
      - type: Pods
        value: 4
        periodSeconds: 3
      selectPolicy: Max
  metrics:
    - type: External
      external:
        metric:
          name: httpproxy_requests_active
          selector:
            matchLabels:
              my-label: "metric-1"
        target: 
          type: AverageValue
          value: "5"
```
