### ISSUE TITLE
badrequest, error: data values must be of type string

### ISSUE THREAD

**Issue by sazzle2611** [fluxcd/kustomize-controller#503]
### Describe the bug

We had flux1 set up with 8 separate gitlab repos supporting 8 different kubernetes clusters.

About a month ago we started migrating to flux2 as the idea of them all sharing base code and just kustomizing the necessary parts was great (when we started we only had 2 clusters and this was far more manageable but it's grown)

This all went really well until we moved one cluster and for some reason this seems to have a problem with all secrets, the error message is in title but an example is
```
Secret/kubernetes-dashboard/kubernetes-dashboard-csrf badrequest, error: data values must be of type string...
```
We haven't touched this secret as it is just part of the original yaml for installing kubernetes-dashboard. The strange thing is it works on all the other 7 clusters sharing exactly the same code!?!

This is the flux version all clusters started out on
```
flux: v0.21.1
helm-controller: v0.12.1
kustomize-controller: v0.16.0
notification-controller: v0.18.1
source-controller: v0.17.2
```
and kubernetes version v1.21.1

I have been trying to debug for the last week and in doing so I upgraded the problem cluster to
```
flux: v0.23.0
helm-controller: v0.13.0
kustomize-controller: v0.18.0
notification-controller: v0.18.1
source-controller: v0.18.0
```
Didn't change anything so I also upgraded kubernetes to v1.22.3
Still didn't help

I have run out of ideas... nearly forgot to mention the important part which is of course I tried putting quotes round the data values, and when that didn't work the keys as well but it didn't make slightest bit of difference

An example of one secret that is fine in all 7 other clusters but not this one is...
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-approle
  namespace: cert-manager
data: 
  secretId: "base64encodedstring"
```
Even without the quotes around the base64encodedstring all of the others work fine.

This secret doesn't already exist in the problem cluster as I deleted it to make sure it wasn't a problem with existing values.

Please help, I really don't want to revert to flux1 for this one cluster but I've run out of ideas for things to try

### Steps to reproduce

Can't tell you how to reproduce as like I said we have done the same for 8 clusters and only 1 is problem. It is also worth noting that apart from the different client sites that they host, this cluster has been configured identically to one of the other working clusters all the way through.

To bootstrap we ran
```
sudo GITLAB_TOKEN=our-token /usr/local/bin/flux bootstrap gitlab \
  --namespace=flux-system \
  --hostname=gitlab.selfhosted.com \
  --owner=admin \
  --repository=flux-system \
  --path=clusters/dev \
  --branch=main \
  --token-auth
```

### Expected behavior

That it should work the same as the others

### OS / Distro

Centos Stream 8

### Flux version

N/A

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.3 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.13.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.18.0
✔ all checks passed

### Git provider

GitLab self hosted

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
@zoomoid have you update your manifests to `kustomize.toolkit.fluxcd.io/v1beta2`? It may be that `v1beta1` had a bug, and when you recreated the Kustomization with `v1beta2` it worked.

**Comment by sazzle2611** [comment]
Thanks @zoomoid do you mean delete all files that have ever been linked to flux2?

I tried uninstalling flux which deleted the namespace flux-system so got rid of all kustomizations then I removed the files for this cluster from the git repo in 'clusters' and bootstrapped it again. I added back infrastructure which was one that didn't have a problem before and this was fine.

I then added back one of the one's that did have a problem with a secret and got the same error. I deleted the namespace for this one and although flux recreated the namespace it still gave the same error for the secret.

I then updated it to kustomize.toolkit.fluxcd.io/v1beta2 but that didn't make difference either.

I've added the secret back manually for now (kubectl apply --server-side -f) and commented it out from the kustomization just so flux would recreate the pods in this namespace.

**Comment by sazzle2611** [comment]
I have rerun the command
```
kubectl apply --server-side -k kubernetes-dashboard
```
after removing the istio gateway and virtual service from the kustomization and this still produced the conflicts but without the last istio error, maybe because it was initially installed with flux1?
I then ran it with --force-conflicts and it worked fine
```
{sarah@titanium}$ kubectl apply --server-side -k kubernetes-dashboard --force-conflicts
namespace/kubernetes-dashboard serverside-applied
serviceaccount/k8s-dashboard-admin serverside-applied
serviceaccount/kubernetes-dashboard serverside-applied
role.rbac.authorization.k8s.io/kubernetes-dashboard serverside-applied
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard serverside-applied
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/k8s-dashboard-admin serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard serverside-applied
configmap/kubernetes-dashboard-settings serverside-applied
secret/kubernetes-dashboard-csrf serverside-applied
secret/kubernetes-dashboard-key-holder serverside-applied
service/dashboard-metrics-scraper serverside-applied
service/kubernetes-dashboard serverside-applied
deployment.apps/dashboard-metrics-scraper serverside-applied
deployment.apps/kubernetes-dashboard serverside-applied
```
Flux is still showing error for csrf secret though. This is what the secret contains
```
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-csrf
  namespace: kubernetes-dashboard
type: Opaque
data:
  csrf: ""
```

**Comment by SomtochiAma** [comment]
The value of csrf key is an empty string?

**Comment by sazzle2611** [comment]
Yeah I believe this is because kubernetes-dashboard updates this itself as when I looked on the other clusters it's not empty, guess this means it shouldn't be in flux in the first place but we've never had problem before.

Part of the role config that comes with the standard kubernetes-dashboard.yaml
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
rules:
  # Allow Dashboard to get, update and delete Dashboard exclusive secrets.
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["kubernetes-dashboard-key-holder", "kubernetes-dashboard-certs", "kubernetes-dashboard-csrf"]
```

**Comment by zoomoid** [comment]
> @zoomoid have you update your manifests to `kustomize.toolkit.fluxcd.io/v1beta2`? It may be that `v1beta1` had a bug, and when you recreated the Kustomization with `v1beta2` it worked.

we upgraded all kustomizations to v1beta2 following the upgrade path. Also, we took an intermediate step via v0.19.0, but I cannot recall if the problem occured there already, might have, I reckon this was some server-side apply field mismatch.

> Thanks @zoomoid do you mean delete all files that have ever been linked to flux2 from all namespaces, just the flux-system one or just the ones with the problem secrets?

I deleted all files created by the kustomization directly responsible for the secret, as well as the kustomization itself. Creating a fresh kustomization with the same secret seemed to cause no issues creating the secret, hence we assumed the faulty bit to be the kustomization.

**Comment by sazzle2611** [comment]
To test I created a completely new kustomization which included a new namespace (test) and one of the secrets that have been failing (gitlab-registry) nothing else at all

The namespace got created but the secret failed with the same error

This is the content of the secret with the data value changed
```
apiVersion: v1
data:
  .dockerconfigjson: base64encodedstring
kind: Secret
metadata:
  name: gitlab-registry
  namespace: test
type: kubernetes.io/dockerconfigjson
```
