### ISSUE TITLE
Semantics of spec.force has changed with server-side apply

### ISSUE THREAD

**Issue by dewe** [fluxcd/kustomize-controller#506]
The new server-side apply doesn't handle `spec.force` the same way as before.

I'm trying to force update a StorageClass, which has been working fine previously with client-side apply. But now it fails with:

```
StorageClass/gp2 dry-run failed, reason: Invalid, error: StorageClass.storage.k8s.io \"gp2\" is invalid: parameters: Forbidden: updates to parameters are forbidden.
```

I'd expect the storage class to be handled just like other immutable resources.

kustomize-controller v0.18.1

**Comment by dewe** [comment]
We're setting field `parameters.encrypted: "true"` and the StorageClass we apply looks like this

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
parameters:
  encrypted: "true"
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

The current StorageClass, that's part of a clean EKS cluster created with `eksctl`, looks like this:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

And this is how it fails:

```bash
$ kubectl apply -f gp2-storageclass.yaml --dry-run=server
The StorageClass "gp2" is invalid: parameters: Forbidden: updates to parameters are forbidden.
```
