### ISSUE TITLE
Support loading a secret with a HashiCorp Vault token to decrypt sops secrets.

### ISSUE THREAD

**Issue by souleb** [fluxcd/kustomize-controller#516]
We want to be able to pass a secret containing a `HashiCorp Vault` token to a `kustomization`. The Kustomization-controller would pass the token to the `Sops Decryptor` for decrypting secrets.

This should work like it does with age and pgp, e.g.
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-secrets
  namespace: default
spec:
  interval: 5m
  path: "./"
  sourceRef:
    kind: GitRepository
    name: my-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-vault-token
```
