### ISSUE TITLE
Reconciliation fails when deploying a kube-prometheus stack (bad dry-run behavior)

### ISSUE THREAD

**Issue by dsogari** [fluxcd/kustomize-controller#531]
This is my Kustomization resource:

```yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/kube-prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

And this is my apps/kube-prometheus directory:

```
kube-prometheus
  kube-prometheus-components.yaml
  kube-prometheus-crds.yaml
  kube-prometheus-namespace.yaml
  kustomization.yaml
```

And this is my kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-namespace.yaml
  - kube-prometheus-crds.yaml
  - kube-prometheus-components.yaml  # template rendering of the kube-prometheus-stack Helm chart (without CRDs)
namespace: monitoring
```

The reconciliation fails because it tries to perform a server-side dry-run, but this would require a service account to be present (chicken-and-egg issue):

> Pod/monitoring/kube-prometheus-grafana-test dry-run failed, reason: Forbidden, error: pods "kube-prometheus-grafana-test" is forbidden: error looking up service account monitoring/kube-prometheus-grafana-test: serviceaccount "kube-prometheus-grafana-test" not found

My environment:

- Kubernetes v1.23.0
- openSUSE MicroOS (Kubic)
- ghcr.io/fluxcd/kustomize-controller:v0.18.2
- kube-prometheus-stack chart version: 30.0.1
