### ISSUE TITLE
kustomize `--enable-helm` flag not supported

### ISSUE THREAD

**Issue by michalschott** [fluxcd/kustomize-controller#548]
I have specific use case where I need to patch helm chart output, I was thinking to follow [this](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md).

```
kustomize build failed: accumulating resources: accumulation err='accumulating resources from './cert-manager': read /tmp/flux-system3546149917/cluster/cert-manager: is a directory': recursed accumulation of path '/tmp/flux-system3546149917/cluster/cert-manager': trouble configuring builtin HelmChartInflationGenerator with config: `
name: cert-manager-issuers
releaseName: cert-manager-cluster-self-signed-issuer-poc
repo: https://charts.adfinis.com
valuesInline:
 clusterIssuers:
 - name: default-tmp
   spec:
     selfSigned: {}
version: 0.2.2
`: must specify --enable-helm
```

Because of existence of helm-controller, not sure if this is even on a radar. Support also depends on helm binary availability (to be executed in subprocess).
