### ISSUE TITLE
Some kustomizations using SOPS have long running times

### ISSUE THREAD

**Issue by log2** [fluxcd/kustomize-controller#600]
Some (*) kustomizations exhibit a running time of 7m30s + a seemingly random fraction of a second, such as:

```
  Normal  ReconciliationSucceeded  52m   kustomize-controller  Reconciliation finished in 7m30.619913479s, next run in 24h0m0s
  Normal  ReconciliationSucceeded  45m   kustomize-controller  Reconciliation finished in 7m30.409957246s, next run in 24h0m0s
```

I'm not sure what the actual cause might be, however I collected a number of examples and counter-examples, which I attach here.

Examples of long reconciliation time (7m30s):

<details>
<summary>SOPS, substituteFrom, secret+HR+PDB</summary>

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: lab-common-mongodb
  namespace: flux-system
spec:
  decryption:
    provider: sops
  force: false
  interval: 24h
  path: ...omitted...
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: kustomization-config
      optional: false
    - kind: ConfigMap
      name: lab-common-kustomization-config
      optional: false
  prune: false
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: staging-lab
  targetNamespace: lab
  timeout: 1m
```

</details>

<details>
<summary>SOPS, substituteFrom, imageRepositories+cronjob+secret+rbac, healthcheck on cronjob</summary>

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: common-imagerepositories
  namespace: flux-system
spec:
  decryption:
    provider: sops
  force: false
  healthChecks:
  - apiVersion: batch/v1
    kind: CronJob
    name: ecr-credentials-sync
    namespace: flux-system
  interval: 24h
  path: ...omitted...
  postBuild:
    substitute:
      accountId: "...omitted..."
      imageRepoNamespace: flux-system
      region: eu-central-1
    substituteFrom:
    - kind: ConfigMap
      name: kustomization-config
      optional: false
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: staging-system
  timeout: 1m
```

</details>

<details>
<summary>SOPS, substituteFrom, gitrepository+HR+secret+configmap (this reaches 15m of reconciliation time) </summary>

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: lab-ha-core
  namespace: flux-system
spec:
  decryption:
    provider: sops
  dependsOn:
  - name: lab-common-prerequisites
    namespace: flux-system
  - name: lab-common-nats
    namespace: flux-system
  - name: lab-common-mongodb
    namespace: flux-system
  - name: lab-ha-prerequisites
    namespace: flux-system
  force: false
  interval: 24h
  path: ...omitted...
  postBuild:
    substitute:
      externalHostnamePrefix: ...omitted...
      externalHostnameSuffix: ...omitted...
      release: ..omitted...
    substituteFrom:
    - kind: ConfigMap
      name: kustomization-config
      optional: false
    - kind: ConfigMap
      name: lab-common-kustomization-config
      optional: false
    - kind: ConfigMap
      name: lab-ha-kustomization-config
      optional: false
    - kind: ConfigMap
      name: lab-common-coturn-params
      optional: false
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: staging-lab
  targetNamespace: lab
  timeout: 1m
```

</details>

Note that, in all previous examples, timeout of 1m for reconciliation is not enforced.

Example of good reconciliation time (<10s):

<details>
<summary>SOPS, secrets</summary>

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
  force: false
  interval: 24h
  path: ./flux-system/secrets
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: staging-flux
  timeout: 1m
```

</details>

Note that, in all examples, no `secretRef` is used to configure SOPS decryptor, due to  https://github.com/fluxcd/kustomize-controller/issues/595
