### ISSUE TITLE
kustomize-controller fails on dry-run with dependsOn being set

### ISSUE THREAD

**Issue by jprecuch** [fluxcd/kustomize-controller#601]
I have some egg/chicken issue with kustomize-controller.

I want to deploy chart and after chart is deployed, create secret. Secret requires chart to be deployed before secret can be created.

I've configured it like this:
1. Chart deploy:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: es-chart-deploy
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./global-infrastructure/helmcharts/external-secrets/helmrelease
```
2. Secret deploy
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: es-css-deploy
  namespace: flux-system
spec:
  dependsOn:
    - name: es-chart-deploy
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./global-infrastructure/helmcharts/external-secrets/cluster-store
```
Once 1 is done it will provide API for second secret deploy. Currently it complains with API missing and no chart is deployed.
```
region-external-secrets False   ClusterSecretStore/main-secretstore dry-run failed, error: no matches for kind "ClusterSecretStore" in version "external-secrets.io/v1alpha1"                                       False
```

Is there some way how to skip kustomize-controller to check for this api until chart is deployed?

**Comment by stefanprodan** [comment]
Please see the docs here: https://fluxcd.io/docs/components/kustomize/kustomization/#kustomization-dependencies

You need to add a health check to the first Kustomization so it waits for the CRDs to be registered, like so:

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: es-chart-deploy
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./global-infrastructure/helmcharts/external-secrets/helmrelease
  wait: true
  timeout: 5m
```
