### ISSUE TITLE
Karpenter provisioner resources are always drifting

### ISSUE THREAD

**Issue by aliusmiles** [fluxcd/kustomize-controller#634]
I have the following karpeneter's provisioner manifest:

<details>
  <summary>default.yaml</summary>
  
  
  ```yaml
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
        - arm64
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
        - t3.small
        - t3.medium
        - t3.large
        - t4g.small
        - t4g.medium
        - t4g.large
  labels:
    kube/nodetype: default
  limits:
    resources:
      cpu: "100"
      memory: 100Gi
  provider:
    subnetSelector:
      karpenter.sh/discovery: development
    securityGroupSelector:
      karpenter.sh/discovery: development
    tags:
      karpenter.sh/discovery: development
      Name: development-default
    amiFamily: Bottlerocket
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          volumeSize: 2Gi
          volumeType: gp3
          deleteOnTermination: true
      - deviceName: /dev/xvdb
        ebs:
          volumeSize: 20Gi
          volumeType: gp3
          deleteOnTermination: true
  ttlSecondsAfterEmpty: 30

  ```
  
</details>

Flux is constantly updating it for some reason, resulting in repeating notifications `Provisioner/default configured` so I'm forced to suspend that kustomization for now.

Flux diff command always returns different result.

 <details>
  <summary>diff results</summary>
  
  
  ```sh

➜  flux diff ks karpenter-provisioner --path deployments/karpenter-provisioner/development
✓  Kustomization diffing...
► Provisioner/default drifted

metadata.generation
  ± value change
    - 24
    + 25

spec.requirements
  ⇆ order changed
    - kubernetes.io/arch, karpenter.sh/capacity-type, node.kubernetes.io/instance-type
    + karpenter.sh/capacity-type, node.kubernetes.io/instance-type, kubernetes.io/arch

spec.requirements.node.kubernetes.io/instance-type.values
  ⇆ order changed
    - t4g.medium, t4g.large, t3.small, t3.medium, t3.large, t4g.small
    + t3.medium, t3.large, t4g.small, t4g.medium, t4g.large, t3.small

⚠️ identified at least one change, exiting with non-zero exit code

➜  flux diff ks karpenter-provisioner --path deployments/karpenter-provisioner/development
✓  Kustomization diffing...
► Provisioner/default drifted

metadata.generation
  ± value change
    - 24
    + 25

spec.requirements.node.kubernetes.io/instance-type.values
  ⇆ order changed
    - t4g.medium, t4g.large, t3.small, t3.medium, t3.large, t4g.small
    + t3.small, t3.medium, t3.large, t4g.small, t4g.medium, t4g.large

⚠️ identified at least one change, exiting with non-zero exit code

  ```
  
</details>

Any ideas where to dig next?

<details>
  <summary>flux check/version</summary>
  
  
  ```sh
➜  flux check
► checking prerequisites
✔ Kubernetes 1.22.6-eks-7d68063 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.20.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.22.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.17.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.24.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.4
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.24.1
✔ all checks passed

➜  flux version
flux: v0.29.3
helm-controller: v0.20.1
image-automation-controller: v0.22.0
image-reflector-controller: v0.17.2
kustomize-controller: v0.24.3
notification-controller: v0.23.4
source-controller: v0.24.1

  ```
  
</details>
