### ISSUE TITLE
Image digest overrides are ignored in kustomization

### ISSUE THREAD

**Issue by abth** [fluxcd/kustomize-controller#652]
I have a Flux Kustomization in which I want to override an image digest:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myenv
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./environments/myenv
  prune: true
  sourceRef:
    kind: GitRepository
    name: myenv
  images:
  - name: myregistry/myimage
    digest: "sha256:12345"
```
Overriding the image tag via `newTag` works, but overriding the digest does not.

Overriding the digest should work according to the documentation here:
https://fluxcd.io/docs/components/kustomize/kustomization/#images
The implementation was done within this ticket:
https://github.com/fluxcd/kustomize-controller/issues/193

I adapted an existing test to reproduce this issue:
https://github.com/abth/flux2/tree/override-image-digest
