### ISSUE TITLE
Timeout is not being enforced for remote apply

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/kustomize-controller#668]
Kustomizations applied against remote clusters are not honouring `Spec.Timeout`.

Based on the `gotk_reconcile_duration_seconds_sum` metric:
![image](https://user-images.githubusercontent.com/5452977/170858236-1aac9508-a412-42ca-b60d-0c7ae3548345.png)

Kustomization YAML:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test-cluster
  namespace: flux-system
spec:
  force: false
  interval: 1m0s
  timeout: 2m0s
  kubeConfig:
    secretRef:
      name: test-kubeconfig
  path: ./clusters/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```
