### ISSUE TITLE
Kustomize-controller error on reconciliation "dry-run failed, error: no matches for kind "ConfigMap" in version "v1"

### ISSUE THREAD

**Issue by Beardface123** [fluxcd/kustomize-controller#674]
All resources that are shared work fine on our previous kustomize-controller version of 0.15.0.   We are attempting to upgrade to 0.25.0 and upon doing so KS objects fail.  This issue is opened for one of those failure messages which is:

```
ConfigMap/kube-system/flux-test1 dry-run failed, error: no matches for kind "ConfigMap" in version "v1"
```

The configmap in question is as follows

`flux-test1.yml`
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: flux-test1
  namespace: kube-system
data:
  main: flux-test1
```
