### ISSUE TITLE
configMapGenerator and secretGenerator with encrypted files don't work in kind: Component

### ISSUE THREAD

**Issue by jceb** [fluxcd/kustomize-controller#680]
I tried to use a SOPS-encrypted environment file with secretGenerator in a Component like the following:

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: my-secret
    envs:
      - config.enc.env
```

`.sops.yaml`:

```yaml
creation_rules:
  - path_regex: .*\.enc\.env$
    pgp: xxxx
```

The `config.enc.env` file is properly encrypted as `dotenv` file When However, when configuration is applied to the cluster, the contents of the secret are not properly decrypted:

```yaml
apiVersion: v1
data:
  MY_SECRET_ACCESS_KEY: xxx_encrypted_data_xxx
  sops_lastmodified: xxx
  sops_mac: xxx
  sops_pgp__list_0__map_created_at: xxx
  sops_pgp__list_0__map_enc: xxx=
  sops_pgp__list_0__map_fp: xxx==
  sops_unencrypted_suffix: xxx
  sops_version: My43LjE=
kind: Secret
metadata:
  name: my-secret-852b7kc8hf
```

The expected result is the following and I'm able to achieve it the moment I change the `kind` and `apiVersion` value in `kustomization.yaml` to `Kustomization`:

```yaml
apiVersion: v1
data:
  MY_SECRET_ACCESS_KEY: decrypted_data
kind: Secret
```

**Comment by jceb** [comment]
Thank you for the information, that makes sense.

**Comment by BertelBB** [comment]
@stefanprodan just curious why Flux silently fails when using Kustomize Components? I mean, you can use it just fine but Flux will not decrypt any secrets created in a Kustomize Component. Took my quite a while to realize that Flux wasn't decrypting the secret because other than that everything seemed to work just fine

**Comment by kevinvalk** [comment]
Today I tested this out and it seems to work in my particular case for a SOPS encrypted .env with a kustomize `secretGenerator`. 

It worked both Flux Kustomize and a normal Kustomize resource!

So I think this can be closed?

**Comment by matheuscscp** [comment]
@kevinvalk Did you use `kind: Component`?

**Comment by kevinvalk** [comment]
> [@kevinvalk](https://github.com/kevinvalk) Did you use `kind: Component`?

Yep included from either a another `apiVersion: kustomize.config.k8s.io/v1beta1, kind: Kustomization` OR `apiVersion: kustomize.toolkit.fluxcd.io/v1, kind: Kustomization`

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: ntfy-authentication
    envs:
      - ntfy-authentication.env
```

P.S. And obviously ntfy-authentication.env is SOPS encrypted.
