### ISSUE TITLE
targetNamespace should create the namespace if not exists

### ISSUE THREAD

**Issue by saltyblu** [fluxcd/kustomize-controller#698]
Currently there is a gap between kustomize and helm. Helm creates the namespaces itself on creation. Kustomize is not doing this. 

I would love to see that as feature in flux/kustomize

**Comment by saltyblu** [comment]
but the flux kustomize could handle that? is this the wrong place than :(

**Comment by saltyblu** [comment]
Also this leads into several issues, if the kustomize exists inside a custom namespace, but this needs to be created by another kustomize out of flux-system.

for example: 

gotk-sync.yaml
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/pt-dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

inside: clusters/pt-dev/playground
component.yaml
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: example-nginx
spec:
  interval: 5m0s
  path: ./deployment/k8s/dev
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: example-nginx
----- kustomize.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: playground
resources:
- component.yaml
```

this deployment will not work because the namepsace playground needs to be created before.

**Comment by hiddeco** [comment]
The kustomize-controller can handle the creation of the namespace (and garbage collection of it) fine, by simply declaring the namespace object in a Kustomization. Whatever other Kustomization then depends on the existence of this namespace, can hierarchically depend on this being applied first using `dependsOn`: https://fluxcd.io/docs/components/kustomize/kustomization/#kustomization-dependencies.

**Comment by kingdonb** [comment]
> This would split a component into two separate kustomize.toolkit.fluxcd.io/v1beta2 inside of two different namespaces

I don't understand this limitation you described. It doesn't limit that way, because the Kustomize controller understands namespaced and non-namespaced resources and the order they should apply. If you create a Namespace inside of a Flux Kustomization, the controller reconciler does the apply in steps: first any Namespaces (and any other Non-Namespaced resources, like CRDs) are created, and second after that any Namespaced Resources and Custom Resources are created.

This is done in steps but in a single transaction via Server-Side Apply, so you should never hit an issue where Kustomize Controller fails to create a resource in the namespace because that namespace had not been declared "upstream." They can be declared in the same Flux Kustomization.

Please reach out if there's some reason this still doesn't meet your needs. I am pretty sure this can be closed.

**Comment by saltyblu** [comment]
just use my example and you will see that flux stop working because the namespace playground does not exists. 

It's a chicken egg issue, putting a kustomization (flux) inside a namespace this ks reconcilation does not work, because flux can't put a flux kustomization into a namespace that does not exist. To solve this, I need to create another kustomization (flux) to create and handle namespaces, which is part of flux-system. Disaster recovery is not possible or onboarding a new cluster. 

There are two steps to implementing a new service inside a new namespace.

**Comment by kingdonb** [comment]
Your example simply seems to be missing the Namespace definition:

```
apiVersion: v1
kind: Namespace
metadata:
  name: playground
```

If you add this definition within the Flux Kustomization **or** adjacent to the Flux Kustomization, assuming nothing else is different from what you've shown here, I am certain that it will work.

I haven't understood clearly what reason you don't want to define the Namespace directly in either one of those places, but unless you have locked down your cluster for Flux's multi-tenancy, there should be nothing stopping you from creating Namespaces where they are needed.

The Flux Kustomization's `targetNamespace` directive will even do you the extra solid of overwriting the `name` field on the `Namespace` definition above, if it's defined inside of the path at the target as some Namespace with any different name. A good example of an overlay which defines its own namespace is in Podinfo, here is the `production` overlay, which pulls in different services from bases, and joins them together in a Namespace that's defined there, within the overlay.

https://github.com/stefanprodan/podinfo/blob/master/deploy/overlays/production/kustomization.yaml

This is the expected pattern, if you have a different approach that didn't work, and you don't understand why, the best way to provide reproduction is with a public repository. Copying and pasting manifests from your partial description inside of a thread is not the ideal way to help you debug your issue.

It is also suggested to start Q&A threads on the [fluxcd/flux2 Discussions Q&A](https://github.com/fluxcd/flux2/discussions/categories/q-a) label.

Feature requests can go there, Proposals are preferred to feature requests, and PRs generally follow after Proposals turn into RFCs, as we like to help folks implement their own "scratch their own itch."

But these proposals must be thought-out and designed, and given to the community with enough space for feedback and understanding the impact. Flux project does try not to make any fast moves outside of planned roadmap issues and other important fixes we encountered on our way to GA.

Please take a look at the example that I linked, and I hope that it helps unblock you. I do not think there's any strong compelling argument or reason to add `targetNamespace` here, it's not compelling to do so just because Helm Controller has this feature. There is no namespace chicken and egg issue for Kustomize controller by itself that I can observe.

**Comment by saltyblu** [comment]
Lets try an example: 
```yaml
clusters/dev/flux-system # default flux-system stuff defining the GitRepo to reconcile 

---
# clusters/dev/example, inside this git repo
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: example-nginx
spec:
  targetNamespace: playground
  interval: 5m0s
  path: ./k8s/dev
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: example-nginx
```

This simple flux example does not work, because the targetNamespace: playground does not exist. 

This means I need to create it first with another flux kustomization that is part of flux-system or if created the default namespace. 
I could also create the namespace inside the main git where everything is stored but this would mix up deployment information and deployments. And the namespace would not be properly versioned anymore. 

The flux-system reconciliation stops completely. I hope that helps.
