### ISSUE TITLE
kustomization running health checks until timeout but should fail earlier

### ISSUE THREAD

**Issue by messiahUA** [fluxcd/kustomize-controller#701]
flux version: v0.31.0
kustomize controller version: v0.26.0

1. there is a Kustomization with a wait and a timeout:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
[...]
wait: true
timeout: 15m
```
2. this Kustomization creates some HelmReleases
3. if HelmRelease upgrade fails (it is reflected in the status) Kustomization continues to run health checks until the timeout (15m), but should fail as soon as HelmRelease fails:
```
NAMESPACE     NAME                        AGE    READY     STATUS
flux-system   somekustomization           111d   Unknown   running health checks with a timeout of 15m0s
```
helmrelease:
```
status:
  conditions:
  - lastTransitionTime: "2022-07-20T11:22:30Z"
    message: upgrade retries exhausted
    reason: UpgradeFailed
    status: "False"
    type: Ready
    reason: UpgradeFailed
    status: "False"
    type: Released
```
This creates an unnecessary delay because Kustomization is blocked until a timeout and neither doesn't apply a new commit nor reacts to any edits.
