### ISSUE TITLE
Patch does nothing when namespace is not defined directly in target resource

### ISSUE THREAD

**Issue by kharf** [fluxcd/kustomize-controller#702]
flux version: v0.31.4
kustomize controller version: v0.26.3

When you have a Flux Kustomization with patches, e.g:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emissary-ingress
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m0s
  dependsOn:
    - name: emissary-ingress-namespace
    - name: linkerd
  sourceRef:
    kind: GitRepository
    name: flux-k8s-stack
  path: "./catalog/emissary-ingress/gke"
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/logging
          value:
            enable: false
      target:
        kind: BackendConfig
        name: emissary-hc-config
        namespace: ingress
```

but the targetted kind does not directly specifiy its namespace and instead its defined in the k8s Kustomization, the patch will not be applied:
```yaml
# backend-configs.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: emissary-hc-config
spec:
  # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 30
  logging:
    enable: true
    sampleRate: 1.0
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    port: 8877
    type: HTTP
    requestPath: /ambassador/v0/check_alive
```

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
resources:
  - ../base
  - backend-configs.yaml
```

I couldn't find anything in the docs, nor in the logs. I'm not sure if that is the correct behaviour, but Flux does not complain, just nothing happens.
In my opinion this should be at least documented.
