### ISSUE TITLE
Global configuration of SOPS Age key

### ISSUE THREAD

**Issue by LittleFox94** [fluxcd/kustomize-controller#707]
Hi,

we are using SOPS to encrypt our secrets for various people who are allowed to see them and a single key per target environment. With this usage, it's a bit tedious to add this snippet to every single flux kustomization:
```yaml
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-key
```

The kustomize-controller already knows when something is encrypted with SOPS (https://github.com/fluxcd/kustomize-controller/blob/e3838182c8c3850cee81522e8dba3f3eab502fee/controllers/kustomization_controller.go#L726-L730), practically eliminating the need for `.spec.decryption.provider`. If the kustomize-controller could add keys from a configured file (perhaps even using the environment variable `SOPS_AGE_KEY_FILE`), configuring this on every kustomization wouldn't be needed anymore.

All this could be added on top of the current API, so no breaking change and specifying another decryption provider or an additional key source would still be possible.

Thanks for making Flux :)

**Comment by stefanprodan** [comment]
In the cluster dir where all the Flux Kustomization are, you can write a patch that adds `decryption ` to all Flux Kustomization that have a common label. This is how it can be done, using a patch in `clusters/my-cluster/kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system # this must be included otherwise Flux will delete itself
  - flux-kustomization-app1.yaml
  - flux-kustomization-app2.yaml
patches:
  - patch: |
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: all
        spec: 
          decryption:
            provider: sops
            secretRef:
              name: sops-key
    target:
      kind: Kustomization
      labelSelector: app.kubernetes.io/sops=enabled
```
