### ISSUE TITLE
Health check timed out although helm release is deployed successfully

### ISSUE THREAD

**Issue by yildizbilal** [fluxcd/kustomize-controller#709]
**Situation**
We have a `kustomization` that deploys a helmrelease named `httpbin` but it shows following error, although deployment was successfully:

`Health check failed after 2m0.013489487s, timeout waiting for: [HelmRelease/wpb-services/httpbin status: 'InProgress']`

I tried to suspend and resume the kustomization, but i get the same error again. Neither the deployment nor the helmrelease logs any error. Couldn't figured out where the `InProgress` cames from.

helm status output: 
```
$ helm status httpbin -n wpb-services
NAME: httpbin
LAST DEPLOYED: Wed Aug  3 10:09:50 2022
NAMESPACE: wpb-services
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Versions**
```
$ flux version
flux: v0.31.5
helm-controller: v0.22.2
image-automation-controller: v0.23.5
image-reflector-controller: v0.19.4
kustomize-controller: v0.26.3
notification-controller: v0.24.1
source-controller: v0.25.11
```
Kubernetes: v1.22.6

**Expected Behaviour**
Kustomizations `READY` flag should be set to `True` and the `STATUS` should show the applied revision.

**Comment by stefanprodan** [comment]
Please post here `flux get helmrelease httpbin -n wpb-services`

**Comment by yildizbilal** [comment]
@stefanprodan

```
$ flux get helmrelease httpbin -n wpb-services
NAME   	REVISION	SUSPENDED	READY	MESSAGE                          
httpbin	2.7.3   	True     	True 	Release reconciliation succeeded
```

**Comment by stefanprodan** [comment]
Can you post here the Flux Kustomization YAML here please

**Comment by yildizbilal** [comment]
```yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-playground
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: k8s-config
  path: ./dev-tools/playground
  dependsOn:
  - name: namespaces
  - name: istio
  - name: chart-sources
  prune: true
  suspend: false
  validation: client
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: grafana
    namespace: wpb-services
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: httpbin
    namespace: wpb-services



```

**Comment by stefanprodan** [comment]
Can you please replace the `healthChecks` with `wait: true` and see if the health check passes.

**Comment by yildizbilal** [comment]
@stefanprodan Same error appears with `wait:true`.

**Comment by somtochiama** [comment]
@yildizbilal Please can you post the status of the helm release?
Run `kubectl get hr httpbin -n wbpservices -oyaml` and paste the status part

**Comment by yildizbilal** [comment]
@somtochiama 

```
status:
  conditions:
  - lastTransitionTime: "2022-08-16T08:46:45Z"
    message: Release reconciliation succeeded
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-08-16T08:46:45Z"
    message: Helm upgrade succeeded
    reason: UpgradeSucceeded
    status: "True"
    type: Released
  helmChart: flux-system/wpb-services-httpbin
  lastAppliedRevision: 2.7.3
  lastAttemptedRevision: 2.7.3
  lastAttemptedValuesChecksum: 0768110ce556fb1611b70804b11285a7ad4bf963
  lastReleaseRevision: 2
  observedGeneration: 6
```
