### ISSUE TITLE
Kustomization unhealthy after upgrade to Flux 0.33

### ISSUE THREAD

**Issue by makkes** [fluxcd/kustomize-controller#717]
I just upgraded to Flux 0.33 on my cluster and one of the Kustomizations is in a weird state:
```
home-e13-dev   320d   False   Health check failed after 5m0.030442677s, timeout waiting for: \
[ImageUpdateAutomation/e13/home-e13-dev status: 'Terminating', ImagePolicy/e13/home-e13-dev status:\ 
'Terminating', ImageRepository/e13/home-e13-dev status: 'Terminating']
```

The Kustomization itself has these health checks defined:
```
[...]
  healthChecks:
  - kind: Deployment
    name: home-e13-dev
    namespace: e13
```
That Deployment is perfectly fine and ready. The IAC resources it complains about are also all ready. I wonder how they would even be able to end up "Terminating". 🤔
