### ISSUE TITLE
validation error: cannot convert int64 to string

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/kustomize-controller#728]
Taking something like this (while validates fine locally) errors in kustomize-controller:
```yaml
- name: fpm-metrics
  image: "hipages/php-fpm_exporter:1"
  imagePullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: /metrics
      port: fpm-metrics
    periodSeconds: 5
  livenessProbe:
    httpGet:
      path: /metrics
      port: fpm-metrics
    periodSeconds: 5
  startupProbe:
    failureThreshold: 120
    periodSeconds: 1
    httpGet:
      path: /metrics
      port: fpm-metrics
  env:
    # FastCGI address where FPM listens on, we're connecting over TCP
    - name: PHP_FPM_SCRAPE_URI
      value: tcp://127.0.0.1:9666/status
    # Address on which to expose metrics and web interface.
    - name: PHP_FPM_WEB_LISTEN_ADDRESS
      value: 6999
```

quoting `value: "6999"` is only way to fix it.
