### ISSUE TITLE
Unable to apply patches to deployments via labelSelector

### ISSUE THREAD

**Issue by ellakk** [fluxcd/kustomize-controller#775]
I want to deploy Flux to OpenShift and therefore need to patch the deployments.
I bootstrap by applying the following Kustomization with `kubectl apply --kustomize cluster/bootstrap/`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/fluxcd/flux2/manifests/install?ref=v0.37.0
patches:
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/securityContext/seccompProfile
      - op: add
        path: /spec/template/spec/containers/0/securityContext/runAsUser
        value: 65534
```
This works, the resources are patched and flux runs.

I then deploy the following resources to manage flux and keep it up to date:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v0.37.0
  url: https://github.com/fluxcd/flux2
  ignore: |
    # exclude all
    /*
    # path to manifests
    !/manifests

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux
  patches:
    - target:
        kind: Deployment
        labelSelector: app.kubernetes.io/part-of=flux
      patch: |-
        - op: remove
          path: /spec/template/spec/containers/0/securityContext/seccompProfile
        - op: add
          path: /spec/template/spec/containers/0/securityContext/runAsUser
          value: 65534
```

The resources are applied without the patches and flux are unable to operate in the OpenShift environment. I Know i can work around this but i wonder if this is a bug.

I've also tried to apply the patches the following way:

```yaml
patches:
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
              - name: manager
                securityContext:
                  runAsUser: 65534
                  seccompProfile:
                    $patch: delete
```

And it's the same story, the patches works when applying with normal Kustomize but not when the kustomize-controller applies them.
