### ISSUE TITLE
Intermittent internalerror, error: data values must be of type string

### ISSUE THREAD

**Issue by RonnanSouza** [fluxcd/kustomize-controller#785]
## The Issue

Since created, this Kustomization has intermittently the presented the issue `Secret/chart-museum/chartmuseum internalerror, error: data values must be of type string`, the secret is created in the cluster already but the error keeps going back and I'm not sure the cause. It's worth mentioning that it is happening for both secrets.

## Artifacts
- Flux Kustomization in the cluster
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  finalizers:
  - finalizers.fluxcd.io
  name: chart-museum
  namespace: chart-museum
spec:
  force: false
  interval: 10m
  path: kubernetes/infra-prod.us-east-1.k8s.tfgco.com/
  prune: true
  serviceAccountName: chart-museum-flux
  sourceRef:
    kind: GitRepository
    name: chart-museum
status:
  conditions:
  - lastTransitionTime: "2023-01-19T21:22:01Z"
    message: 'Applied revision: master/9bd3b362b2ba2e1e5be445789515d02e04015313'
  inventory:
    entries:
    - id: chart-museum_chartmuseum-values-k9kg8k94d2__ConfigMap
      v: v1
    - id: chart-museum_redis-values-t8mm48m4d4__ConfigMap
      v: v1
    - id: chart-museum_chartmuseum__Secret
      v: v1
    - id: chart-museum_redis-password__Secret
      v: v1
    - id: chart-museum_chartmuseum_helm.toolkit.fluxcd.io_HelmRelease
      v: v2beta1
    - id: chart-museum_redis_helm.toolkit.fluxcd.io_HelmRelease
      v: v2beta1
```
- kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chart-museum
resources:
  - chartmuseum/helmrelease.yaml
  - chartmuseum/secret.yaml
  - redis/helmrelease.yaml
  - redis/secret.yaml
configMapGenerator:
  - name: chartmuseum-values
    files:
      - values.yaml=./chartmuseum/values.yaml
  - name: redis-values
    files:
      - values.yaml=./redis/values.yaml
configurations:
  - kustomizeconfig.yaml
```
- secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: chartmuseum
type: Opaque
data:
  AWS_ACCESS_KEY_ID: XXX
  ...
```
- applying secret with kubectl
```bash
 kubectl apply -f chartmuseum/secret.yaml --server-side
error: Apply failed with 5 conflicts: conflicts with "kustomize-controller":
- .data.AWS_ACCESS_KEY_ID
- .data.AWS_SECRET_ACCESS_KEY
- .data.BASIC_AUTH_PASS
- .data.BASIC_AUTH_USER
- .data.CACHE_REDIS_PASSWORD
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
```

## Flux Check
► checking prerequisites
✗ flux 0.37.0 <0.38.3 (new version is available, please upgrade)
✔ Kubernetes 1.23.12 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.27.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed
