### ISSUE TITLE
Constant config drift on webhook rules expansion

### ISSUE THREAD

**Issue by mbrancato** [fluxcd/kustomize-controller#792]
Every time I upgrade Knative, I need to manually expand the webhook rules because on apply, they are modified and no longer match the manifest.

e.g.
https://github.com/knative/serving/blob/25de8121f169719c52e609308f701f45ddba5166/config/core/webhooks/domainmapping-validation.yaml
https://github.com/knative/serving/blob/646d0b1a9626cf636faf3e9b3a58bdd8eeb90ee5/config/core/webhooks/defaulting.yaml

The rules start out like this:

```yaml
rules:
  - apiGroups:
      - serving.knative.dev
    apiVersions:
      - "*"
    operations:
      - CREATE
      - UPDATE
    scope: "*"
    resources:
      - domainmappings
      - domainmappings/status
```

and are modified to this:
```yaml
rules:
  - apiGroups:
      - serving.knative.dev
    apiVersions:
    - v1alpha1
    operations:
      - CREATE
      - UPDATE
    scope: "*"
    resources:
      - domainmappings
      - domainmappings/status
  - apiGroups:
      - serving.knative.dev
    apiVersions:
    - v1beta1
    operations:
      - CREATE
      - UPDATE
    scope: "*"
    resources:
      - domainmappings
      - domainmappings/status
```

I've previously opened issues in other projects without progress:
https://github.com/knative/serving/issues/13449
https://github.com/kubernetes/kubernetes/issues/107318
