### ISSUE TITLE
kustomize-controller getting OOMKilled

### ISSUE THREAD

**Issue by vytautaskubilius** [fluxcd/kustomize-controller#801]
After deploying a handful of Kustomizations I have noticed that the `kustomize-controller` pods were being OOMKilled on every reconciliation. At the moment our deployment has 12 Kustomizations in total, and the only way I've found to keep the pods stable was to increase their memory limit to 4Gi. The pod now seems to consistently sit at ~3.5Gi of used memory:

```
kubectl -n flux-system top pods
NAME                                           CPU(cores)   MEMORY(bytes)
helm-controller-67b65ff599-8tp9l               2m           64Mi
image-automation-controller-7f9b499997-v92q8   5m           31Mi
image-reflector-controller-65f575dbd-5rf2q     13m          91Mi
kustomize-controller-bddb7f558-h44ff           1m           3311Mi
notification-controller-654c5d586b-w2x84       1m           13Mi
source-controller-59498d9f8d-pkztj             13m          79Mi
```

`flux stats -A` doesn't appear to show anything out of ordinary:

```
flux stats -A
RECONCILERS          	RUNNING	FAILING	SUSPENDED	STORAGE
GitRepository        	1      	0      	0        	54.0 KiB
OCIRepository        	0      	0      	0        	-
HelmRepository       	6      	0      	0        	3.6 MiB
HelmChart            	6      	0      	0        	768.6 KiB
Bucket               	0      	0      	0        	-
Kustomization        	12     	0      	0        	-
HelmRelease          	6      	0      	0        	-
Alert                	0      	0      	0        	-
Provider             	0      	0      	0        	-
Receiver             	0      	0      	0        	-
ImageUpdateAutomation	1      	0      	0        	-
ImagePolicy          	11     	0      	0        	-
ImageRepository      	11     	0      	0        	-
```

While the pod is stable for the time being, in the next few weeks we will be deploying more applications (~250 in total), and I'm worried that Flux won't be able to scale if memory usage increases linearly with the amount of Kustomizations that we will be deploying.

I'm attaching a [heap profile](https://fluxcd.io/flux/gitops-toolkit/debugging/#collecting-a-profile) from the pod taken while it was reporting high memory usage in case it's helpful - [`heap.tar.gz`](https://github.com/fluxcd/kustomize-controller/files/10841644/heap.tar.gz).

Is the `kustomize-controller` pod supposed to consume this much memory? If not, is there any more data I could collect and provide to help with troubleshooting?

**Comment by hiddeco** [comment]
The shared `.tar.gz` does not appear to contain a valid heap profile.

```console
$ go tool pprof -http=:8082 heap.out
heap.out: parsing profile: unrecognized profile format
failed to fetch any source profiles
```

**Comment by hiddeco** [comment]
In addition, it would help if we would know the precise version of the controller you are making use of.

**Comment by vytautaskubilius** [comment]
Thanks for the quick responses! With regards to the Kustomizations, they don't contain anything too special:

- The resources that get deployed are Deployments, ExternalSecrets (sadly, still using the deprecated [KES](https://github.com/external-secrets/kubernetes-external-secrets) instead of [ESO](https://external-secrets.io/v0.7.2/)), PodDisruptionBudgets, Services and Ingresses (using AWS ALB Ingress Controller). 
- We use Kustomize's `configMapGenerator`s to generate ConfigMaps with ~20 environment variables that get fed to the pods.
- There is a slightly annoying amount of layers to the Kustomizations - i.e. there is a base with two overlays, and then each of those overlays have another two overlays of their own. The extra overlays have minimal changes - mainly just adding specific resource allocations and probes to the pods, replica counts, name suffixes, labels. 

Here is an example of the pod health checks:
```
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep "[s]idekiq"
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5

        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep "[s]idekiq"
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5

        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep "[s]idekiq"
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
```

Speaking of the cluster, there's a reasonable amount of stuff in there that's not (yet) part of Flux (though the intention is to migrate it all to be managed with Flux in the upcoming weeks):

- ~1300 pods across all namespaces.
  - Not sure if it matters, but ~1000 of those pods are in the `default` namespace (very suboptimal, but no immediate plans to fix this).
- Runs K8s 1.22 on AWS EKS with ~30-40 nodes at any given time in total.

That's all that comes to mind, but do let me know if there is any other information that could be useful!
