### ISSUE TITLE
dry-run failed, error: failed to prune fields: failed add back owned items: failed to convert pruned object at version notification.toolkit.fluxcd.io/v1beta2: conversion for notification.toolkit.fluxcd.io/v1beta2, Kind=Alert returned invalid metadata in object at index 1: missing metadata in converted object

### ISSUE THREAD

**Issue by danports** [fluxcd/kustomize-controller#843]
I'm getting this error every reconciliation for a couple of my Kustomization resources and I'm not sure why. The problem started today with no apparent cause; I hadn't pushed any changes to the resource nor upgraded any Flux components recently.

Here's one of the resources reporting this error:
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: system-deployments
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: kube-system
```

I've tried restarting the Kustomize controller and deleting the Alert resource and neither has made a difference. I don't see anything pertinent in the Kustomize controller logs. I'm using the latest version of all Flux components (v0.35.1 for the Kustomize controller). Anything else I can try?
