### ISSUE TITLE
Repeated "Namespace/tst configured" event

### ISSUE THREAD

**Issue by mjroeleveld** [fluxcd/kustomize-controller#871]
About every 5 minutes, I get a notification in Slack saying:

> kustomization/flux-system.flux-system:
> Namespace/tst configured

I see no reason why this is happening. This message started to show when I added another, differently named namespace. It seems a state bug. Any way I can reset this?

**Comment by stefanprodan** [comment]
It may be that 2 Flux Kustomizations fight over the same resources. You can use `flux tree ks` and see who manages them. I recommend you follow the repo structure showcased here: https://github.com/fluxcd/flux2-kustomize-helm-example

**Comment by mjroeleveld** [comment]
This is about the structure we use. 
<img width="203" alt="image" src="https://github.com/fluxcd/kustomize-controller/assets/5803704/305cd9c4-8840-4043-850a-ae1578826300">
I'm getting the following CLI error (should I create a new issue?): `failed to get API group resources: unable to retrieve the complete list of server APIs: kustomize.toolkit.fluxcd.io/v1: the server could not find the requested resource`

**Comment by mjroeleveld** [comment]
I downgraded flux CLI to RC.4 but I get the same error: 
```
❯ flux tree kustomization environment-tst
✗ failed to get API group resources: unable to retrieve the complete list of server APIs: kustomize.toolkit.fluxcd.io/v1: the server could not find the requested resource

❯ flux --version
flux version 2.0.0-rc.4
```

**Comment by stefanprodan** [comment]
You need to upgrade your cluster to the same version as the CLI

**Comment by mjroeleveld** [comment]
Maybe I'm missing something but they seem the same:
```bash

❯ flux version --client
flux: v2.0.0-rc.4

❯ flux version
flux: v2.0.0-rc.4
helm-controller: v0.28.1
image-automation-controller: v0.28.0
image-reflector-controller: v0.23.1
kustomize-controller: v0.32.0
notification-controller: v0.30.2
source-controller: v0.33.0
```

**Comment by mjroeleveld** [comment]
I will try to upgrade the cluster, as I am running an old version.

**Comment by mjroeleveld** [comment]
I see now, using `flux tree kustomization flux-system` I see that the namespace is included in two kustomizations. Thanks!

**Comment by mjroeleveld** [comment]
It's still unexpected, because the namespace is included in a kustomization that should not include it (I think):
<img width="277" alt="image" src="https://github.com/fluxcd/kustomize-controller/assets/5803704/bc8d5863-104d-4f8d-8b2e-c4725a8c4ff3">
`environment.yml`:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: environment-tst
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: repositories
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/environments/tst
  prune: true
  wait: true
  timeout: 5m0s
```
`path` points to a directory that does not include `Namespace/tst`, but it is listed under both `Kustomization/flux-system/environment-tst` _and_ `Kustomization/flux-system/flux-system`. I would expect only the latter, as the namespace is not present in the `environment-tst` kustomization.
