### ISSUE TITLE
 issue with update deployment where, tcp/udp ports same

### ISSUE THREAD

**Issue by uderik** [fluxcd/kustomize-controller#923]
Hi All!
We have issue with update deployment where, tcp/udp ports same
```
    image: prom/statsd-exporter
    imagePullPolicy: Always
    name: sonorus-statsd-exporter
    ports:
    - containerPort: 9102
      protocol: TCP
    - containerPort: 9125
      protocol: TCP
    - containerPort: 9125
      protocol: UDP
```
i get an error
```
kustomization/app-da.flux-system
Deployment/deepaffects-servers/sonorus-sync-server dry-run failed, error: failed to create manager for existing fields: failed to convert new object (deepaffects-servers/sonorus-sync-server; apps/v1, Kind=Deployment) to smd typed: .spec.template.spec.containers[name="sonorus-statsd-exporter"].ports: duplicate entries for key [containerPort=9125,protocol="UDP"]
```
i'am delete deployment and run flux reconcile, this fixed the issue until the next deployment update

flux check                                            
► checking prerequisites
```
✗ flux 0.41.2 <2.0.0 (new version is available, please upgrade)
✔ Kubernetes 1.25.10-eks-c12679a >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► fluxcd/helm-controller:v0.30.0
✔ image-automation-controller: deployment ready
► fluxcd/image-automation-controller:v0.30.0
✔ image-reflector-controller: deployment ready
► fluxcd/image-reflector-controller:v0.25.0
✔ kustomize-controller: deployment ready
► fluxcd/kustomize-controller:v0.34.0
✔ notification-controller: deployment ready
► fluxcd/notification-controller:v0.32.0
✔ source-controller: deployment ready
► fluxcd/source-controller:v0.35.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed
```
