### ISSUE TITLE
Kubernetes built-in kind: Pod in Kustomization healthChecks doesn't work 

### ISSUE THREAD

**Issue by Angel0r** [fluxcd/kustomize-controller#931]
Hey!

I want to get healthChecks for all the pods but this doesn't work.
My healthCheck on my Kustomization is:
```
    healthChecks:
        - apiVersion: apps/v1
          kind: Pod
          name: '*'
          namespace: test
```
I get the following error:
```
Health check failed after 30.01012045s: timeout waiting for: [Pod/test/* status: 'Unknown': no matches for kind "Pod" in group "apps"]
```
Then I thought it was the star that may doesn't work in Kustomization. So I wrote it like below:
```
    healthChecks:
        - apiVersion: apps/v1
          kind: Pod
          name: podName-1234abc
          namespace: test
```
However, I got the following error:
```
Health check failed after 30.019454691s: timeout waiting for: [Pod/test/podName-1234abc status: 'Unknown': no matches for kind "Pod" in group "apps"]
```
Is it a bug or am I missing something?

/Angelos

**Comment by stefanprodan** [comment]
Flux is not made to manage pods directly, use a Job/Deployment/etc

**Comment by Angel0r** [comment]
I am following this documentation:
https://fluxcd.io/flux/components/kustomize/kustomization/#health-checks

What do you mean by that? Where should I use that, in the "name:"?
```
    healthChecks:
        - apiVersion: apps/v1
          kind: Pod
          name: pod/podName-1234abc
          namespace: test
```

**Comment by somtochiama** [comment]
@Angel0r you are specifying the wrong apiVersion.

Can you try:
```
healthChecks:
    - apiVersion: v1
      kind: Pod
      name: pod/podName-1234abc
      namespace: test
```
