### ISSUE TITLE
Secret error: data values must be of type string when using mittwald / kubernetes-replicator

### ISSUE THREAD

**Issue by DanielAntos90** [fluxcd/kustomize-controller#946]
Kustumize-controller validation of secret fails when mittwald / kubernetes-replicator is used. 

I have used object below, which should be valid according to documentation https://github.com/mittwald/kubernetes-replicator, but still I get error: data values must be of type string. 

I have tried to run kugectl apply -f on this object without any issue. 
Also kubeconform didn't return any error when I have tried it on local.

```
apiVersion: v1   
data: {}  
kind: Secret   
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-from: logistics/usr-logistics--business-support--product-availability-reservation-orchestrator--product-catalog-worker
  name: usr-logistics--business-support--product-availability-reservation-orchestrator--product-catalog-worker
  namespace: business-support
```
