### ISSUE TITLE
[Question/Bug] Nesting/adding new kustomization under main flux-system one does not change ownership but "duplicates" resources

### ISSUE THREAD

**Issue by kbelosevic** [fluxcd/kustomize-controller#974]
Following are steps I tried to do:
(Idea is to move already deployed HelmReleases and plain k8s manifests under new kustomization)

Initial state / already deployed and working:

### Initial state

Git repo and main kustomization
```
# This manifest was generated by flux. DO NOT EDIT.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/foo/git_repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/cluster-name
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

```

Linux `tree`
```
git_repo/clusters/cluster-name/
├── flux-system
│   ├── gotk-components.yaml
│   ├── gotk-sync.yaml
│   ├── kustomization.yaml
│   └── patch
│       ├── add-sops-decryption.yaml
│       ├── adjust-helm-controller-resources.yaml
│       ├── adjust-image-automation-controller-resources.yaml
│       ├── adjust-image-reflector-controller-resources.yaml
│       ├── adjust-kustomize-controller-resources.yaml
│       ├── adjust-notification-controller-resources.yaml
│       └── adjust-source-controller-resources.yaml
└── releases
    └── apps
        └── test-deployment
            ├── helmrelease.yaml
            ├── post-migrate-job.yaml
            └── pre-migrate-job.yaml
```

Flux `flux tree -n flux-system flux-system`
```
Kustomization/flux-system/flux-system
├── Namespace/flux-system
├── ResourceQuota/flux-system/critical-pods-flux-system
├── ServiceAccount/flux-system/helm-controller
├── ServiceAccount/flux-system/image-automation-controller
├── ServiceAccount/flux-system/image-reflector-controller
├── ServiceAccount/flux-system/kustomize-controller
├── ServiceAccount/flux-system/notification-controller
├── ServiceAccount/flux-system/source-controller
├── ClusterRole/crd-controller-flux-system
├── ClusterRole/flux-edit-flux-system
├── ClusterRole/flux-view-flux-system
├── ClusterRoleBinding/cluster-reconciler-flux-system
├── ClusterRoleBinding/crd-controller-flux-system
├── Service/flux-system/notification-controller
├── Service/flux-system/source-controller
├── Service/flux-system/webhook-receiver
├── Deployment/flux-system/helm-controller
├── Deployment/flux-system/image-automation-controller
├── Deployment/flux-system/image-reflector-controller
├── Deployment/flux-system/kustomize-controller
├── Deployment/flux-system/notification-controller
├── Deployment/flux-system/source-controller
├── Job/test-deployment-ns/post-migrate-job
├── Job/test-deployment-ns/pre-migrate-job
├── HelmRelease/test-deployment-ns/test-deployment
│   ├── ServiceAccount/test-deployment-ns/test-deployment-sa
│   ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-media-pvc
│   ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-assets-pvc
│   ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-protected-pvc
│   └── Deployment/test-deployment-ns/test-deployment
├── NetworkPolicy/flux-system/allow-egress
├── NetworkPolicy/flux-system/allow-scraping
├── NetworkPolicy/flux-system/allow-webhooks
└── GitRepository/flux-system/flux-system
```

### Desired goal:
Idea is with this to control deploy order following -  [Running pre and post-deployment jobs with Flux](https://fluxcd.io/flux/use-cases/running-jobs/)
```
git_repo/clusters/cluster-name/
├── flux-system
│   ├── gotk-components.yaml
│   ├── gotk-sync.yaml
│   ├── kustomization.yaml
│   └── ........
└── releases
    └── apps
        └── test-deployment
            ├── deployment-order-kustomization.yaml
            ├── deploy
            │   └── helmrelease.yaml
            ├── post-deploy
            │   └── post-migrate-job.yaml
            └── pre-deploy
                └── pre-migrate-job.yaml
```

File `deployment-order-kustomization.yaml`

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-deployment-pre-deploy
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./clusters/cluster-name/releases/apps/test-deployment/pre-deploy"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-deployment-deploy
  namespace: flux-system
spec:
  dependsOn:
    - name: test-deployment-pre-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./clusters/cluster-name/releases/apps/test-deployment/deploy"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-deployment-post-deploy
  namespace: flux-system
spec:
  dependsOn:
    - name: test-deployment-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./clusters/cluster-name/releases/apps/test-deployment/post-deploy"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true

```

## Issue
What happens next (did try to follow renaming ks / moving to different directory from [documentation/faq](https://fluxcd.io/flux/faq/#how-can-i-safely-move-resources-from-one-dir-to-another)

`flux tree ks -n flux-system flux-system`
```
Kustomization/flux-system/flux-system
├── Namespace/flux-system
├── ResourceQuota/flux-system/critical-pods-flux-system
├── ServiceAccount/flux-system/helm-controller
├── ServiceAccount/flux-system/image-automation-controller
├── ServiceAccount/flux-system/image-reflector-controller
├── ServiceAccount/flux-system/kustomize-controller
├── ServiceAccount/flux-system/notification-controller
├── ServiceAccount/flux-system/source-controller
├── ClusterRole/crd-controller-flux-system
├── ClusterRole/flux-edit-flux-system
├── ClusterRole/flux-view-flux-system
├── ClusterRoleBinding/cluster-reconciler-flux-system
├── ClusterRoleBinding/crd-controller-flux-system
├── Service/flux-system/notification-controller
├── Service/flux-system/source-controller
├── Service/flux-system/webhook-receiver
├── Deployment/flux-system/helm-controller
├── Deployment/flux-system/image-automation-controller
├── Deployment/flux-system/image-reflector-controller
├── Deployment/flux-system/kustomize-controller
├── Deployment/flux-system/notification-controller
├── Deployment/flux-system/source-controller
├── Job/test-deployment-ns/post-migrate-job
├── Job/test-deployment-ns/pre-migrate-job
├── HelmRelease/test-deployment-ns/test-deployment
│   ├── ServiceAccount/test-deployment-ns/test-deployment-sa
│   ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-media-pvc
│   ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-assets-pvc
│   ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-protected-pvc
│   └── Deployment/test-deployment-ns/test-deployment
├── Kustomization/flux-system/test-deployment-deploy
│   └── HelmRelease/test-deployment-ns/test-deployment
│       ├── ServiceAccount/test-deployment-ns/test-deployment-sa
│       ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-media-pvc
│       ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-assets-pvc
│       ├── PersistentVolumeClaim/test-deployment-ns/test-deployment-common-protected-pvc
│       └── Deployment/test-deployment-ns/test-deployment
├── Kustomization/flux-system/test-deployment-post-deploy
│   └── Job/test-deployment-ns/post-migrate-job
├── Kustomization/flux-system/test-deployment-pre-deploy
│   └── Job/test-deployment-ns/pre-migrate-job
├── NetworkPolicy/flux-system/allow-egress
├── NetworkPolicy/flux-system/allow-scraping
├── NetworkPolicy/flux-system/allow-webhooks
└── GitRepository/flux-system/flux-system
```

Everything regarding my resources is "duplicated", i.e.
```
├── Job/test-deployment-ns/post-migrate-job
# and then in same tree output
├── Kustomization/flux-system/test-deployment-post-deploy
│   └── Job/test-deployment-ns/post-migrate-job
```

So now by `flux tree` I have "duplicated" resources (they are not actually deployed multiple times) and have constant "battle" in reconciliation between `flux-system` and `test-deployment-[post|pre|]-deploy` kustomizations as to who is "owner"

Tried:
- adding file `deployment-order-kustomization.yaml` both prior and after moving files to directories post/pre/deploy
- suspending main ks and then adding
- adding file `deployment-order-kustomization.yaml` with empty directories and then organising into post/pre/deploy
- tried having those kustomizations in a separate directory each in its own file
```
├── deploy
│   └── helmrelease.yaml
├── kustomizations
│   ├── deployment.yaml
│   ├── post-deploy.yaml
│   └── pre-deploy.yaml
├── post-deploy
│   └── post-migrate-job.yaml
└── pre-deploy
    └── pre-migrate-job.yaml
```

Only way ownership of those objects (helmrelease, jobs, etc) is changed is if I move them fully outside of `clusters/cluster-name/` to a new directory and refference them with kustomization that points to them.

So can someone please assist as in to what I am doing wrong?
