### ISSUE TITLE
List type variables substituted as single element

### ISSUE THREAD

**Issue by r2ronoha** [fluxcd/kustomize-controller#988]
When using a list as a variable to substitute, it is then applied to the yaml as a single element string, with the items of the list space separated, rather than a yaml list

**Test**:
* Config map
```
apiVersion: v1
data:
  subnet_ids: '[subnet-1 subnet-2 subnet-3]'
```
* Object definition
```
apiVersion: rds.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  name: test-subnetIds
spec:
  forProvider:
    region: us-east-1
    subnetIds: ${subnet_ids}
```
  * where the subnetIds is an array of string (extract of CRD subnetgroups.rds.aws.upbound.io)
```
                  subnetIds:
                    description: A list of VPC subnet IDs.
                    items:
                      type: string
                    type: array
```
* Rendered yaml
```
spec:
  deletionPolicy: Delete
  forProvider:
    description: Managed by Terraform
    region: us-east-1
    subnetIds:
    - subnet-1 subnet-2 subnet-3
```
* Expected rendered yaml
```
spec:
  deletionPolicy: Delete
  forProvider:
    description: Managed by Terraform
    region: us-east-1
    subnetIds:
    - subnet-1
    - subnet-2
    - subnet-3
```

**Notes**
* the value is consumed as a list, as using a string (`subnet-1,subnet-2,subnet-3`) as `subnet_ids` with the same definitions results in error `.spec.forProvider.subnetIds: expected list, got &{subnet-1,subnet-2,subnet-3}...`
